//===--- Haydn.h - Declare Haydn target feature support -----------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares Haydn TargetInfo objects.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H
#define LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H

#include "clang/Basic/MacroBuilder.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/TargetParser/Triple.h"

namespace clang {
namespace targets {

/// Haydn target class (haydn-unknown-elf baremetal DSP)
///
/// ISA feature names match llvm/lib/Target/Haydn/HaydnFeatures.td:
///   agu | circular-buffer | bit-reversed | hwloop | simd
///
/// Processor models (HaydnGeneric.td):
///   -mcpu / -target-cpu: generic and haydn are the same full ISA
///     (agu + circular-buffer + bit-reversed + hwloop + simd).
///   -mtune / -tune-cpu (product default haydn): schedule model only.
///
/// Builtin availability is gated via BuiltinsHaydn.td Features= strings
/// against this map.
/// getTargetDefines emits __HAYDN_ARCH__ + per-ISA capability macros
/// (agu / circular-buffer / bit-reversed / hwloop / simd) plus the
/// soft-float identity (__SOFTFP__ / __HAYDN_SOFT_FLOAT__). Never exposes
/// bundle FormatID, slot suffixes, or AltDesc.
class LLVM_LIBRARY_VISIBILITY HaydnTargetInfo : public TargetInfo {
  // Product baseline is the full ISA. Only an explicit -target-feature
  // minus can turn a bit off (handleTargetFeatures).
  bool HasAGU = true;
  bool HasCircularBuffer = true;
  bool HasBitReversed = true;
  bool HasHWLoop = true;
  bool HasSIMD = true;

  std::string CPU;

public:
  HaydnTargetInfo(const llvm::Triple &Triple, const TargetOptions &Opts);

  StringRef getABI() const override { return "ilp32"; }
  bool setABI(const std::string &Name) override { return Name == "ilp32"; }

  bool setCPU(const std::string &Name) override {
    if (!isValidCPUName(Name))
      return false;
    CPU = Name;
    return true;
  }

  bool isValidCPUName(StringRef Name) const override;
  void fillValidCPUList(SmallVectorImpl<StringRef> &Values) const override;
  bool isValidTuneCPUName(StringRef Name) const override {
    return isValidCPUName(Name);
  }
  void fillValidTuneCPUList(SmallVectorImpl<StringRef> &Values) const override {
    fillValidCPUList(Values);
  }

  void getTargetDefines(const LangOptions &Opts,
                        MacroBuilder &Builder) const override;

  llvm::SmallVector<Builtin::InfosShard> getTargetBuiltins() const override;

  bool hasFeature(StringRef Feature) const override;

  bool
  initFeatureMap(llvm::StringMap<bool> &Features, DiagnosticsEngine &Diags,
                 StringRef CPU,
                 const std::vector<std::string> &FeaturesVec) const override;

  bool handleTargetFeatures(std::vector<std::string> &Features,
                            DiagnosticsEngine &Diags) override;

  /// Haydn uses a two-bank calling convention (GPR R1–R7 for i32/ptr and
  /// DR D0–D3 for i64/f64/SIMD) for both fixed AND variadic args.
  /// A single `void *` va_list cursor cannot independently walk two register
  /// banks, and va_copy needs independent cursor advancement. We therefore use
  /// the AArch64-style structured __builtin_va_list (5 fields: __stack,
  /// __gr_top, __vr_top, __gr_offs, __vr_offs), interpreting __vr_top/__vr_offs
  /// as the DR bank. Layout is generated by ASTContext from this enum kind
  /// (no upstream Clang infrastructure change). VASTART (HaydnAsmPrinter)
  /// initializes all five fields and the custom G_VAARG selector
  /// (HaydnInstructionSelector) bank-selects.
  BuiltinVaListKind getBuiltinVaListKind() const override {
    return AArch64ABIBuiltinVaList;
  }

  bool validateAsmConstraint(const char *&Name,
                             TargetInfo::ConstraintInfo &Info) const override;
  bool validateOutputSize(const llvm::StringMap<bool> &FeatureMap,
                          StringRef Constraint, unsigned Size) const override;
  bool validateInputSize(const llvm::StringMap<bool> &FeatureMap,
                         StringRef Constraint, unsigned Size) const override;

  std::string_view getClobbers() const override { return ""; }

  bool hasBitIntType() const override { return true; }

  /// Haydn baremetal enters through `main` even under -ffreestanding (BSP
  /// startup calls main); keep C99 5.1.2.2.3 fallthrough-to-zero so
  /// gcc-torture freestanding builds return 0 instead of undef.
  bool treatsMainAsEntryUnderFreestanding() const override { return true; }

protected:
  ArrayRef<const char *> getGCCRegNames() const override;
  ArrayRef<GCCRegAlias> getGCCRegAliases() const override;
};

} // namespace targets
} // namespace clang

#endif // LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H
