//===--- Haydn.h - Declare Haydn target feature support -----------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares Haydn TargetInfo objects.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H
#define LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H

#include "clang/Basic/MacroBuilder.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/StringRef.h"

namespace clang {
namespace targets {

/// Haydn target class (haydn-unknown-elf baremetal DSP)
class LLVM_LIBRARY_VISIBILITY HaydnTargetInfo : public TargetInfo {
public:
  HaydnTargetInfo(const llvm::Triple &Triple, const TargetOptions &Opts);

  StringRef getABI() const override { return "ilp32"; }
  bool setABI(const std::string &Name) override { return Name == "ilp32"; }

  void getTargetDefines(const LangOptions &Opts,
                        MacroBuilder &Builder) const override;

  llvm::SmallVector<Builtin::InfosShard> getTargetBuiltins() const override;

  /// D178 / L146: Haydn uses a two-bank calling convention (GPR R1–R7 for
  /// i32/ptr and DR D0–D3 for i64/f64/SIMD) for both fixed AND variadic args.
  /// A single `void *` va_list cursor cannot independently walk two register
  /// banks, and va_copy needs independent cursor advancement. We therefore use
  /// the AArch64-style structured __builtin_va_list (5 fields: __stack,
  /// __gr_top, __vr_top, __gr_offs, __vr_offs), interpreting __vr_top/__vr_offs
  /// as the DR bank. This avoids any upstream Clang infrastructure change (Hard
  /// Constraint #0): the struct layout is generated by ASTContext from this
  /// enum kind. VASTART (HaydnAsmPrinter) initializes all five fields and the
  /// custom G_VAARG selector (HaydnInstructionSelector) bank-selects.
  BuiltinVaListKind getBuiltinVaListKind() const override {
    return AArch64ABIBuiltinVaList;
  }

  bool validateAsmConstraint(const char *&Name,
                             TargetInfo::ConstraintInfo &Info) const override;

  std::string_view getClobbers() const override { return ""; }

  bool hasBitIntType() const override { return true; }

protected:
  ArrayRef<const char *> getGCCRegNames() const override;
  ArrayRef<GCCRegAlias> getGCCRegAliases() const override;
};

} // namespace targets
} // namespace clang

#endif // LLVM_CLANG_LIB_BASIC_TARGETS_HAYDN_H
