; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Coverage for addr mode ptr add.


;
; NOTE: updated for VLIW slot-1 load promotion — independent loads now pack as ld32+ld32.
;
; Tests for G_PTR_ADD constant offset optimization.
;
; When G_PTR_ADD has a constant offset, the selector should use ADDI32
; instead of ADD32, avoiding the need to materialize the constant into
; a register first. This is a peephole optimization in the selector.
;
; Pattern: G_PTR_ADD base, constant -> ADDI32 dst, base, constant
; (instead of: materialize constant; ADD32 dst, base, materialized_reg)

;G_PTR_ADD with small constant offset (fits simm16)
; The pointer is used later, so the ADDI32 cannot be folded into a load.
; It should still use ADDI32 rather than ADD32 with a materialized constant.

define ptr @test_ptradd_const_offset(ptr %p) {
; CHECK-LABEL: test_ptradd_const_offset:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, 40 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %ptr = getelementptr i32, ptr %p, i32 10
  ret ptr %ptr
}

;G_PTR_ADD with negative constant offset
define ptr @test_ptradd_neg_offset(ptr %p) {
; CHECK-LABEL: test_ptradd_neg_offset:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, -20 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %ptr = getelementptr i32, ptr %p, i32 -5
  ret ptr %ptr
}

;G_PTR_ADD with variable offset (should use register arithmetic)
; The mul-to-shift optimization converts MUL x, 4 to SLL x, 2, then ADD.
define ptr @test_ptradd_var_offset(ptr %p, i32 %off) {
; CHECK-LABEL: test_ptradd_var_offset:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; slli32 r2, r2, 2 }
; CHECK-NEXT:    { nop; add32 r1, r1, r2 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %ptr = getelementptr i32, ptr %p, i32 %off
  ret ptr %ptr
; Variable offset with power-of-2 element size uses shift+add (not MAC)
}

;Sequential array access pattern
; Load from p[0], p[1], p[2] — each with a different constant offset.
; The loads should fold the offsets, and no separate address computation
; instructions should be emitted for the constant-offset accesses.
define i32 @test_sequential_loads(ptr %p) {
; CHECK-LABEL: test_sequential_loads:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { ld32 r3, r1, 1; ld32 r2, r1, 0 }
; CHECK-NEXT:    { nop; ld32 r1, r1, 2 }
; CHECK-NEXT:    { nop; add32 r2, r2, r3 }
; CHECK-NEXT:    { nop; add32 r1, r2, r1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %v0 = load i32, ptr %p
  %p1 = getelementptr i32, ptr %p, i32 1
  %v1 = load i32, ptr %p1
  %p2 = getelementptr i32, ptr %p, i32 2
  %v2 = load i32, ptr %p2
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %s1, %v2
  ret i32 %s2
}

;Store then load from same offset (store-to-load forwarding test)
define i32 @test_store_load_same_offset(ptr %p, i32 %val) {
; CHECK-LABEL: test_store_load_same_offset:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; s_sw_pre_imm r2, r1, 4 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r1, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %ptr = getelementptr i32, ptr %p, i32 4
  store i32 %val, ptr %ptr
  %v = load i32, ptr %ptr
  ret i32 %v
; Store and load should both use offset 16
; NOTE: the lone load may be promoted to ld32 (slot-1 over-promotion,); both
; ld32 and ld32 are semantically identical loads, so this is acceptable.
}

;2D array access with one constant dimension
; arr[i][3] where i is variable: offset = 3*4 = 12, but base varies.
; The inner dimension offset should be folded.
define i32 @test_2d_array_const_col(ptr %arr, i32 %row) {
; CHECK-LABEL: test_2d_array_const_col:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r3, r0, 20 }
; CHECK-NEXT:    { nop; mull r2, r2, r3 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; add32 r2, r1, r2 }
; CHECK-NEXT:    { nop; s_lw_pre_imm r1, r2, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %rowptr = getelementptr [5 x i32], ptr %arr, i32 %row
  %elem = getelementptr [5 x i32], ptr %rowptr, i32 0, i32 3
  %v = load i32, ptr %elem
  ret i32 %v
; The column offset (3 * 4 = 12) should be folded into the load
}
