; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — baremetal _start function and basic runtime support.

; REBASELINED : / pipeline reorder (ExpandPseudos/BitSimplify pre-scheduler + materialize at leaveRegion) — bundles regrouped, ops unchanged.

;
; Test baremetal _start function and basic runtime support.
; This verifies that the CodeGen can handle the _start entry point
; and that basic operations work for baremetal programs.

;_start function (entry point)

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define void @_start() {
; CHECK-LABEL: _start:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, -4
; CHECK-NEXT:    { nop; jal lr, main }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %retval = call i32 @main()
  ret void
}

;main function
define i32 @main() {
; CHECK-LABEL: main:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 42 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  ret i32 42
}

;Test that global data works
@global_val = global i32 123, align 4

define i32 @use_global() {
; CHECK-LABEL: use_global:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, %hi12(global_val) }
; CHECK-NEXT:    { nop; addi32 r1, r1, %lo20(global_val) }
; CHECK-NEXT:    { nop; ld32 r1, r1, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %val = load i32, ptr @global_val, align 4
  ret i32 %val
}

;Test BSS-style zero-initialized data
@zero_val = global i32 0, align 4

define i32 @use_zero() {
; CHECK-LABEL: use_zero:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, %hi12(zero_val) }
; CHECK-NEXT:    { nop; addi32 r1, r1, %lo20(zero_val) }
; CHECK-NEXT:    { nop; ld32 r1, r1, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %val = load i32, ptr @zero_val, align 4
  ret i32 %val
}
