; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s
;
; Test byval parameter passing.
; byval arguments are passed as pointers to the stack location where the
; argument data resides. The callee loads from the pointer to access fields.
;
; REBASELINE : byval lowering is correct. Prior XFAIL was a stale
; CHECK expecting `ld64` for i64; the backend splits i64 loads to dual `ld32`
; + DR pack (d_ldw_post_imm), which is a valid (if not ideal) lowering.

%struct.big = type { i32, i32, i32, i32, i32 }

declare void @use_i32(i32)

;byval struct with 5 fields (exceeds register capacity)
define void @byval_big(ptr byval(%struct.big) %p) nounwind {
; CHECK-LABEL: byval_big:
; CHECK:       // #<spill-kpi> @byval_big spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    { s_lw_with_imm r1, r1, 0; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.big, ptr %p, i32 0, i32 0
  %v0 = load i32, ptr %e0
  call void @use_i32(i32 %v0)
  ret void
}

;byval with field access
define i32 @byval_sum_fields(ptr byval(%struct.big) %p) nounwind {
; CHECK-LABEL: byval_sum_fields:
; CHECK:       // #<spill-kpi> @byval_sum_fields spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { s_lw_with_imm r2, r1, 0; nop; s_lw_with_imm r1, r1, 1 }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.big, ptr %p, i32 0, i32 0
  %e1 = getelementptr %struct.big, ptr %p, i32 0, i32 1
  %v0 = load i32, ptr %e0
  %v1 = load i32, ptr %e1
  %sum = add i32 %v0, %v1
  ret i32 %sum
}

;byval with all fields
define i32 @byval_all_fields(ptr byval(%struct.big) %p) nounwind {
; CHECK-LABEL: byval_all_fields:
; CHECK:       // #<spill-kpi> @byval_all_fields spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { s_lw_with_imm r2, r1, 0; nop; s_lw_with_imm r3, r1, 1 }
; CHECK-NEXT:    { s_lw_with_imm r4, r1, 2; nop; s_lw_with_imm r5, r1, 3 }
; CHECK-NEXT:    { s_lw_with_imm r1, r1, 4; add32 r2, r2, r3; nop }
; CHECK-NEXT:    { add32 r2, r2, r4; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r5; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.big, ptr %p, i32 0, i32 0
  %e1 = getelementptr %struct.big, ptr %p, i32 0, i32 1
  %e2 = getelementptr %struct.big, ptr %p, i32 0, i32 2
  %e3 = getelementptr %struct.big, ptr %p, i32 0, i32 3
  %e4 = getelementptr %struct.big, ptr %p, i32 0, i32 4
  %v0 = load i32, ptr %e0
  %v1 = load i32, ptr %e1
  %v2 = load i32, ptr %e2
  %v3 = load i32, ptr %e3
  %v4 = load i32, ptr %e4
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %s1, %v2
  %s3 = add i32 %s2, %v3
  %sum = add i32 %s3, %v4
  ret i32 %sum
}

;byval with i64 array
%struct.i64pair = type { i64, i64 }

define i64 @byval_i64_struct(ptr byval(%struct.i64pair) %p) nounwind {
; Dual ld32 of lo/hi halves (current GISel path); d_ldw packs to DR64.
; CHECK-LABEL: byval_i64_struct:
; CHECK:       // #<spill-kpi> @byval_i64_struct spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { addi32 r2, r1, 4; s_lw_with_imm r1, r1, 0 }
; CHECK-NEXT:    { s_lw_with_imm r2, r2, 0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, sp, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, sp, 1 }
; CHECK-NEXT:    { d_ldw_with_imm d0, sp, 0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.i64pair, ptr %p, i32 0, i32 0
  %v0 = load i64, ptr %e0
  ret i64 %v0
}

;Multiple byval parameters
define i32 @byval_multi(ptr byval(%struct.big) %p1, ptr byval(%struct.big) %p2) nounwind {
; CHECK-LABEL: byval_multi:
; CHECK:       // #<spill-kpi> @byval_multi spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { s_lw_with_imm r1, r1, 0; nop; s_lw_with_imm r2, r2, 0 }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { add32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.big, ptr %p1, i32 0, i32 0
  %e1 = getelementptr %struct.big, ptr %p2, i32 0, i32 0
  %v0 = load i32, ptr %e0
  %v1 = load i32, ptr %e1
  %sum = add i32 %v0, %v1
  ret i32 %sum
}

;byval with write-through
define void @byval_write(ptr byval(%struct.big) %p) nounwind {
; CHECK-LABEL: byval_write:
; CHECK:       // #<spill-kpi> @byval_write spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { addi32 r2, r0, 42; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 0 }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %e0 = getelementptr %struct.big, ptr %p, i32 0, i32 0
  store i32 42, ptr %e0
  ret void
}
