; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s
;
; Indirect calls lower to jalr.



@funcs = external global [4 x ptr]
declare i32 @direct_callee(i32)

define i32 @test_basic_indirect(ptr %fp, i32 %x) {
; CHECK-LABEL: test_basic_indirect:
; CHECK:       // #<spill-kpi> @test_basic_indirect spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r3, r1; move32 r1, r2; nop }
; CHECK-NEXT:    { nop; jalr lr, r3, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = call i32 %fp(i32 %x)
  ret i32 %r
}

;Indirect call with two arguments

define i32 @test_indirect_2arg(ptr %fp, i32 %a, i32 %b) {
; CHECK-LABEL: test_indirect_2arg:
; CHECK:       // #<spill-kpi> @test_indirect_2arg spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r4, r1; move32 r1, r2; nop }
; CHECK-NEXT:    { move32 r2, r3; nop; nop }
; CHECK-NEXT:    { nop; jalr lr, r4, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = call i32 %fp(i32 %a, i32 %b)
  ret i32 %r
}

;Void function pointer call

define void @test_void_fp(ptr %fp) {
; CHECK-LABEL: test_void_fp:
; CHECK:       // #<spill-kpi> @test_void_fp spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { nop; jalr lr, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  call void %fp()
  ret void
}

;Chained indirect calls (same fp called twice)

define i32 @test_chained_indirect(ptr %fp, i32 %x) {
; CHECK-LABEL: test_chained_indirect:
; CHECK:       // #<spill-kpi> @test_chained_indirect spills=2 spill-bytes=8 reloads=2 reload-bytes=8
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { addi32 r3, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r3, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r3, 1 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r8, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r2; nop }
; CHECK-NEXT:    { nop; jalr lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jalr lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r1 = call i32 %fp(i32 %x)
  %r2 = call i32 %fp(i32 %r1)
  ret i32 %r2
}

;Function pointer loaded from global array

define i32 @test_fp_from_array(i32 %idx) {
; CHECK-LABEL: test_fp_from_array:
; CHECK:       // #<spill-kpi> @test_fp_from_array spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { lui r2, funcs; slli32 r3, r1, 2; nop }
; CHECK-NEXT:    { addi32 r2, r2, funcs; nop }
; CHECK-NEXT:    { s_lw_pre_reg r3, r2, r3; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; jalr lr, r3, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %p = getelementptr [4 x ptr], ptr @funcs, i32 0, i32 %idx
  %fp = load ptr, ptr %p
  %r = call i32 %fp(i32 %idx)
  ret i32 %r
}

;Indirect call with many arguments (forces stack spilling)

define i32 @test_indirect_many_args(ptr %fp, i32 %a) {
; CHECK-LABEL: test_indirect_many_args:
; CHECK:       // #<spill-kpi> @test_indirect_many_args spills=4 spill-bytes=16 reloads=4 reload-bytes=16
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { addi32 r3, sp, 24; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r3, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r3, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r3, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r3, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset r8, 36
; CHECK-NEXT:    .cfi_offset r9, 32
; CHECK-NEXT:    .cfi_offset r10, 28
; CHECK-NEXT:    .cfi_offset lr, 24
; CHECK-NEXT:    { addi32 r9, r0, 8; subi32 sp, sp, 16 }
; CHECK-NEXT:    { addi32 r8, r0, 1; move32 r10, sp }
; CHECK-NEXT:    { addi32 r12, r0, 2; s_sw_post_imm r9, r10, 2 }
; CHECK-NEXT:    { addi32 r3, r0, 3; s_sw_with_imm r2, r10, 0 }
; CHECK-NEXT:    { addi32 r4, r0, 4; addi32 r5, r0, 5 }
; CHECK-NEXT:    { addi32 r6, r0, 6; addi32 r7, r0, 7 }
; CHECK-NEXT:    { move32 r9, r1; move32 r1, r8; nop }
; CHECK-NEXT:    { move32 r2, r12; nop; nop }
; CHECK-NEXT:    { nop; jalr lr, r9, 0; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; xor32 r0, r0, r0 }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 6; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 7; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 8; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 9; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = call i32 %fp(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 %a)
  ret i32 %r
}

;Mix of direct and indirect calls in the same function

define i32 @test_mixed_calls(ptr %fp, i32 %x) {
; CHECK-LABEL: test_mixed_calls:
; CHECK:       // #<spill-kpi> @test_mixed_calls spills=3 spill-bytes=12 reloads=3 reload-bytes=12
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32 r3, sp, 12; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r3, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r3, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r3, 2 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset r8, 20
; CHECK-NEXT:    .cfi_offset r9, 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r2; nop }
; CHECK-NEXT:    { nop; jal lr, direct_callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 r9, r1; nop }
; CHECK-NEXT:    { nop; jalr lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add32 r1, r9, r1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r1 = call i32 @direct_callee(i32 %x)
  %r2 = call i32 %fp(i32 %r1)
  %result = add i32 %r1, %r2
  ret i32 %result
}
