; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Indirect calls lower to jalr_w.

; Indirect calls lower to jalr_w.

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped


@funcs = external global [4 x ptr]
declare i32 @direct_callee(i32)

define i32 @test_basic_indirect(ptr %fp, i32 %x) {
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; CHECK-LABEL: test_basic_indirect:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r3, r1; move32 r1, r2 }
; CHECK-NEXT:    { jalr_w lr, r3, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call i32 %fp(i32 %x)
  ret i32 %r
}

;Indirect call with two arguments

define i32 @test_indirect_2arg(ptr %fp, i32 %a, i32 %b) {
; CHECK-LABEL: test_indirect_2arg:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r4, r1; move32 r1, r2 }
; CHECK-NEXT:    { move32 r2, r3; nop }
; CHECK-NEXT:    { jalr_w lr, r4, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call i32 %fp(i32 %a, i32 %b)
  ret i32 %r
}

;Void function pointer call

define void @test_void_fp(ptr %fp) {
; CHECK-LABEL: test_void_fp:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { jalr_w lr, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  call void %fp()
  ret void
}

;Chained indirect calls (same fp called twice)

define i32 @test_chained_indirect(ptr %fp, i32 %x) {
; CHECK-LABEL: test_chained_indirect:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { addi32_w r3, sp, 8; nop }
; CHECK-NEXT:    { st32 lr, r3, 0; nop }
; CHECK-NEXT:    { st32 r8, r3, 1; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r8, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r2 }
; CHECK-NEXT:    { jalr_w lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { jalr_w lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 2; nop }
; CHECK-NEXT:    { ld32 r8, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r1 = call i32 %fp(i32 %x)
  %r2 = call i32 %fp(i32 %r1)
  ret i32 %r2
}

;Function pointer loaded from global array

define i32 @test_fp_from_array(i32 %idx) {
; CHECK-LABEL: test_fp_from_array:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 2; nop }
; CHECK-NEXT:    { lui r3, funcs; nop }
; CHECK-NEXT:    { addi32_w r3, r3, funcs; nop }
; CHECK-NEXT:    { sll32 r2, r1, r2; nop }
; CHECK-NEXT:    { s_lw_pre_reg r2, r3, r2; nop }
; CHECK-NEXT:    { jalr_w lr, r2, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %p = getelementptr [4 x ptr], ptr @funcs, i32 0, i32 %idx
  %fp = load ptr, ptr %p
  %r = call i32 %fp(i32 %idx)
  ret i32 %r
}

;Indirect call with many arguments (forces stack spilling)

define i32 @test_indirect_many_args(ptr %fp, i32 %a) {
; CHECK-LABEL: test_indirect_many_args:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { addi32_w r3, sp, 28; nop }
; CHECK-NEXT:    { st32 lr, r3, 0; nop }
; CHECK-NEXT:    { st32 r9, r3, 1; nop }
; CHECK-NEXT:    { st32 r8, r3, 2; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset r8, 36
; CHECK-NEXT:    .cfi_offset r9, 32
; CHECK-NEXT:    .cfi_offset lr, 28
; CHECK-NEXT:    { subi32 sp, sp, 16; move32 r12, r1 }
; CHECK-NEXT:    { addi32_w r1, r0, 8; nop }
; CHECK-NEXT:    { move32 r9, sp; move32 r8, r2 }
; CHECK-NEXT:    { st32_post r1, r9, 2; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 1; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 2; nop }
; CHECK-NEXT:    { addi32_w r3, r0, 3; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 4; nop }
; CHECK-NEXT:    { addi32_w r5, r0, 5; nop }
; CHECK-NEXT:    { addi32_w r6, r0, 6; nop }
; CHECK-NEXT:    { addi32_w r7, r0, 7; nop }
; CHECK-NEXT:    { st32 r8, r9, 0; nop }
; CHECK-NEXT:    { jalr_w lr, r12, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 7; nop }
; CHECK-NEXT:    { ld32 r9, sp, 8; nop }
; CHECK-NEXT:    { ld32 r8, sp, 9; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 40; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call i32 %fp(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 %a)
  ret i32 %r
}

;Mix of direct and indirect calls in the same function

define i32 @test_mixed_calls(ptr %fp, i32 %x) {
; CHECK-LABEL: test_mixed_calls:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32_w r3, sp, 12; nop }
; CHECK-NEXT:    { st32 lr, r3, 0; nop }
; CHECK-NEXT:    { st32 r9, r3, 1; nop }
; CHECK-NEXT:    { st32 r8, r3, 2; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset r8, 20
; CHECK-NEXT:    .cfi_offset r9, 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r2 }
; CHECK-NEXT:    { jal_w lr, direct_callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { move32 r9, r1; nop }
; CHECK-NEXT:    { jalr_w lr, r8, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { add32 r1, r9, r1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { ld32 r9, sp, 4; nop }
; CHECK-NEXT:    { ld32 r8, sp, 5; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 24; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r1 = call i32 @direct_callee(i32 %x)
  %r2 = call i32 %fp(i32 %r1)
  %result = add i32 %r1, %r2
  ret i32 %result
}
