; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -verify-machineinstrs -global-isel-abort=1 %s -o - | FileCheck %s

; Test basic function call - callee-saved register handling

; Test basic function call prologue/epilogue




define void @test_dr64_callee_saved() {
; CHECK-LABEL: test_dr64_callee_saved:
; CHECK:       // #<spill-kpi> @test_dr64_callee_saved spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { nop; jal lr, callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  call void @callee()
  ret void
}

; Test basic function call prologue/epilogue
define void @test_gpr_callee_saved() {
; CHECK-LABEL: test_gpr_callee_saved:
; CHECK:       // #<spill-kpi> @test_gpr_callee_saved spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { nop; jal lr, callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  call void @callee()
  ret void
}

declare void @callee()
