; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -verify-machineinstrs -global-isel-abort=1 %s -o - | FileCheck %s

; Role: semantic — basic function call - callee-saved register handling.

; Test basic function call - callee-saved register handling

; Test basic function call prologue/epilogue

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define void @test_dr64_callee_saved() {
; CHECK-LABEL: test_dr64_callee_saved:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { jal_w lr, callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  call void @callee()
  ret void
}

; Test basic function call prologue/epilogue
define void @test_gpr_callee_saved() {
; CHECK-LABEL: test_gpr_callee_saved:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { jal_w lr, callee; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  call void @callee()
  ret void
}

declare void @callee()
