; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -O2 -global-isel-abort=1 \
; RUN:     -verify-machineinstrs < %s | FileCheck %s
;
; — land 0/-1 + add + store must stay correct without
; GenMux Pattern 2. EarlyIfConv may or may not convert (side blocks that
; load are not speculated); either a movt/movf or a branch+move of -1 is
; fine. What must not happen: load through the land register.

@a = external global i16
@out = external global i16
@flag = external global i32
@alt = external global i16
@ptr = external global ptr

define void @land_add_store() nounwind {
; CHECK-LABEL: land_add_store:
; CHECK:       // #<spill-kpi> @land_add_store spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { lui r1, a; lui r2, flag; nop }
; CHECK-NEXT:    { addi32 r1, r1, a; addi32 r2, r2, flag }
; CHECK-NEXT:    { s_lhwu_with_imm r4, r1, 0; lui r1, out; nop }
; CHECK-NEXT:    { s_lw_with_imm r5, r2, 0; addi32 r3, r0, 0 }
; CHECK-NEXT:    { addi32 r1, r1, out; not32 r2, r4 }
; CHECK-NEXT:    { seq32 r4, r5, r3; nop; nop }
; CHECK-NEXT:    { bnez r4, .LBB0_4; nop; nop }
; CHECK-NEXT:  // %bb.1: // %cond.true
; CHECK-NEXT:    { lui r4, alt; nop; nop }
; CHECK-NEXT:    { addi32 r4, r4, alt; nop }
; CHECK-NEXT:    { s_lhwu_with_imm r4, r4, 0; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { seq32 r4, r4, r3; nop; nop }
; CHECK-NEXT:    { bnez r4, .LBB0_3; nop; nop }
; CHECK-NEXT:  .LBB0_2: // %land.rhs
; CHECK-NEXT:    { addi32 r3, r0, -1; nop }
; CHECK-NEXT:  .LBB0_3: // %land.end
; CHECK-NEXT:    { add32 r2, r3, r2; nop; nop }
; CHECK-NEXT:    { nop; nop; s_shw_with_imm r2, r1, 0 }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
; CHECK-NEXT:  .LBB0_4: // %cond.false
; CHECK-NEXT:    { lui r3, ptr; nop; nop }
; CHECK-NEXT:    { addi32 r3, r3, ptr; nop }
; CHECK-NEXT:    { s_lw_with_imm r3, r3, 0; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { s_lhwu_with_imm r4, r3, 0; nop; nop }
; CHECK-NEXT:    { addi32 r3, r0, 0; nop }
; CHECK-NEXT:    { seq32 r4, r4, r3; nop; nop }
; CHECK-NEXT:    { beqz r4, .LBB0_2; nop; nop }
; CHECK-NEXT:    { beqz r0, .LBB0_3; nop; nop }
entry:
  %a0 = load i16, ptr @a
  %not = xor i16 %a0, -1
  %f = load i32, ptr @flag
  %tobool = icmp eq i32 %f, 0
  br i1 %tobool, label %cond.false, label %cond.true

cond.true:
  %v = load i16, ptr @alt
  %cmp = icmp eq i16 %v, 0
  br i1 %cmp, label %land.end, label %land.rhs

cond.false:
  %p = load ptr, ptr @ptr
  %pv = load i16, ptr %p
  %cmp2 = icmp eq i16 %pv, 0
  br i1 %cmp2, label %land.end, label %land.rhs

land.rhs:
  br label %land.end

land.end:
  %land = phi i16 [ 0, %cond.false ], [ 0, %cond.true ], [ -1, %land.rhs ]
  %sum = add i16 %land, %not
  store i16 %sum, ptr @out
  ret void
}

; Result is always land + ~a stored — integer path, not pointer.
