; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Constant materialisation via HaydnMatInt (ISA-43 #1 /).

; REGRESSION TEST: Constant materialisation via HaydnMatInt (ISA-43 #1 /).
;
; The Haydn ISA LUI is 12-bit-shift: LUI rt,imm12 -> rt = imm12 << 20 (bits
; [31:20]); ADDI32 is simm16; ORI32 is uimm16. The selector chains each sequence
; from R0 (soft-zero = 0): ADDI32 rd,R0,imm = sext(imm); ORI32 rd,R0,imm = imm;
; LUI rd,R0,imm = imm12<<20. So:
; simm16 -> 1 ADDI32
; 0..65535 -> 1 ORI32 (from R0)
; >1MiB / upper-only -> LUI [+ ADDI32] (1-2 instrs)
; everything else -> `lui hi12` + `addi32{{(_w)?}} simm20` (12+20 split covers
; the whole 32-bit space; canonical pair post-ASO-removal)
; Every constant below was verified by simulating the emitted sequence from R0
; and confirming it reconstructs the exact 32-bit value.

;================================================================
;Power-of-2 / small constants
;================================================================

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define i32 @const_pow2_2() {
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; CHECK-LABEL: const_pow2_2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 2 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 2
}

define i32 @const_pow2_0x100000() {
; const_pow2_0x100000:
; 0x100000 = 1<<20 -> LUI 1 + addi32{{(_w)?}} 0 (canonical LUI pair; bit20 set)
; CHECK-LABEL: const_pow2_0x100000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 1 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 1048576
}

define i32 @const_0x80000000() {
; const_0x80000000:
; INT_MIN = 1<<31 -> single LUI 0x800
; CHECK-LABEL: const_0x80000000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 2048 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -2147483648
}

;================================================================
;THE BUG (ISA-43 #1): 0xF0000000 must load correctly.
;Pre-fix the backend emitted `lui 61440` (16-bit); hardware did
;(61440 & 0xFFF)<<20 = 0. Now it emits `lui 3840` (0xF00) -> 0xF0000000.
;(MatInt always emits the LUI+addi32{{(_w)?}} pair form when LUI is chosen.)
;================================================================

define i32 @const_0xF0000000() {
; CHECK-LABEL: const_0xF0000000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 3840 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -268435456
}

;================================================================
;Upper-half-only values (low 16 bits zero). With simm20 range
;0xFFFF0000 = -65536 and 0x00010000 = +65536 are single ADDI32_W
;(the simm20 from R0 reconstructs the full 32-bit value).
;================================================================

define i32 @const_upper_0xFFFF0000() {
; CHECK-LABEL: const_upper_0xFFFF0000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, -65536 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -65536
}

define i32 @const_upper_0x00010000() {
; CHECK-LABEL: const_upper_0x00010000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 65536 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 65536
}

;================================================================
;simm16 boundary -> single ADDI32_W
;================================================================

define i32 @const_simm16_max() {
; CHECK-LABEL: const_simm16_max:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 32767 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 32767
}

define i32 @const_simm16_min() {
; CHECK-LABEL: const_simm16_min:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, -32768 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -32768
}

;================================================================
;uimm16 (32768..65535) -> single ADDI32_W from R0
;(simm20 covers these unsigned-looking values; ORI32 is no longer used.)
;================================================================

define i32 @const_0x8000() {
; CHECK-LABEL: const_0x8000:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 32768 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 32768
}

define i32 @const_0xFFFF() {
; CHECK-LABEL: const_0xFFFF:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 65535 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 65535
}

;================================================================
;Full 32-bit -> `lui hi12` + `addi32{{(_w)?}} simm20` (2-instruction pair).
;Round-trips when (hi12<<20 + simm20) reconstructs V.
;================================================================

define i32 @const_0x12345678() {
; CHECK-LABEL: const_0x12345678:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 291 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 284280 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 305419896
}

define i32 @const_0xDEADBEEF() {
; CHECK-LABEL: const_0xDEADBEEF:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 3563 }
; CHECK-NEXT:    { nop; addi32 r1, r1, -147729 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -559038737
}

define i32 @const_0x10001() {
; const_0x10001:
; 0x10001 fits in simm20 -> single addi32{{(_w)?}} from R0.
; CHECK-LABEL: const_0x10001:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 65537 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 65537
}

;================================================================
;Constants used in arithmetic
;================================================================

define i32 @add_pow2_small(i32 %x) {
; CHECK-LABEL: add_pow2_small:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, 4 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = add i32 %x, 4
  ret i32 %r
}

define i32 @add_pow2_large(i32 %x) {
; add_pow2_large:
; 65536 fits in simm20 -> single addi32{{(_w)?}} from R0, then add32
; add32 verified at line 306 above.
; CHECK-LABEL: add_pow2_large:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, 65536 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = add i32 %x, 65536
  ret i32 %r
}

define i32 @or_large_const(i32 %x) {
; or32 verified at line 326 above.
; CHECK-LABEL: or_large_const:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; ori32 r1, r1, 65536 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = or i32 %x, 65536
  ret i32 %r
}
