; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1  -verify-machineinstrs  -enable-misched=false -enable-post-misched=false < %s | FileCheck %s

; Role: smoke — function labels present; compile+emit smoke, not semantic qualification.

; REBASELINED : scheduling changed (//) — bundles regrouped, ops unchanged.
; REBASELINED 2026-08-14: MAC MemberId cutover — FMULA co-issues; idle
; `{ nop; nop }` after MAC parcels dropped.
; Format-E-only rebaseline (/R2-R5): CHECK-LABEL + key invariants.
; Format E rebaseline: labels + present opcodes.

; Format E: function labels present (compile + emit smoke).

declare i64 @llvm.haydn.mulfp32x16x2ras.low(i64, i64, i64)

; LD64 fold: the intrinsic loads %x as i64, which the selector decomposes to
; LD64 + MOV_DR64_TO_GPR (unpack). The fold collapses this to two LD32.
; Without a follow-up ADDI32 of the base, the fold fires.
; NOTE: loads may be promoted to ld32 (slot-1 promotion,) when they pack.
; The base may be sp (stack spill) or a GPR — match either.
define i64 @test_ld64_fold(ptr %in, i64 %coef) {
; CHECK-LABEL: test_ld64_fold:
; CHECK-DAG: ld32
; CHECK-DAG: addi32{{.*}}, 4
; CHECK-DAG: fmula16
; CHECK: jalr
  %x = load i64, ptr %in
  %r = call i64 @llvm.haydn.mulfp32x16x2ras.low(i64 0, i64 %x, i64 %coef)
  ret i64 %r
}

; ST64 fold: the intrinsic produces an i64 result that is stored. The
; selector emits MOV_GPR_TO_DR64 (pack) + ST64. The fold collapses to 2 ST32.
define void @test_st64_fold(ptr %out, i64 %a, i64 %coef) {
; CHECK-LABEL: test_st64_fold:
; CHECK-DAG: fmula16
; CHECK-DAG: addi32{{.*}}, 4
; CHECK-DAG: d_sw_l_with_imm
; CHECK-DAG: d_sw_h_with_imm
; CHECK: jalr
  %r = call i64 @llvm.haydn.mulfp32x16x2ras.low(i64 0, i64 %a, i64 %coef)
  store i64 %r, ptr %out
  ret void
}
