; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 < %s \
; RUN:     | FileCheck %s

; REGRESSION TEST : retire Mode-0 alias producers XOR32_M0
; ST32_M0S0LS / LD32_M0S0LS in HaydnAsmPrinter. These were emitted directly
; as MCInsts (post-finalizer) for the re-zero-R0 idiom (XOR32_M0 after calls)
; and the varargs va_list setup (ST32_M0S0LS / LD32_M0S0LS in VASTART/VACOPY).
; They have NO _S<k>_FLEX variant, so the forcing function fires:
; "Haydn MC: opcode 'XOR32_M0' (opNNN) has no Bundle128 form"
;
; Fix : emit the legacy base names XOR32 / ST32 / LD32 instead. These
; auto-pair via the FlexMap suffix-strip rule to XOR32_S0
; ST32_S0 / LD32_S0 (the Family 2 defs). The 3 GPR32/imm
; operands bind positionally; the Bundle128 encoder resolves the flex variant.
;
; Test design: (1) a function with a call exercises the post-call re-zero-R0
; XOR32 emit; (2) a varargs function exercises VASTART (ST32) and VACOPY
; (LD32 + ST32). If the producer regresses to the M0 alias, llc aborts at
; emission with the forcing-function error. The CHECKs confirm the.s parses
; and the mnemonics land (xor32 / st32 / ld32, NOT xor32_m0 / st32_m0s0ls).

;f_call
; The post-call re-zero emits xor32 (r0,r0,r0). The bundle printer may render
; it standalone or in a bundle; check the mnemonic appears.
define dso_local i32 @f_call(i32 %a) {
; CHECK-LABEL: f_call:
; CHECK:       // #<spill-kpi> @f_call spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { nop; jal lr, ext; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
  %r = tail call i32 @ext(i32 %a)
  ret i32 %r
}
declare dso_local i32 @ext(i32)

;f_varargs
; VASTART emits st32 (va_list field stores); VACOPY emits ld32 + st32 pairs.
define dso_local void @f_varargs(i32 %n, ...) {
; CHECK-LABEL: f_varargs:
; CHECK:       // #<spill-kpi> @f_varargs spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 96; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    { addi32 r1, sp, 72; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 0 }
; CHECK-NEXT:    { addi32 r2, sp, 40; s_sw_with_imm r3, r1, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r4, r1, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r5, r1, 3 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r6, r1, 4 }
; CHECK-NEXT:    { nop; nop; s_sw_pre_imm r7, r1, 5 }
; CHECK-NEXT:    { addi32 r1, sp, 8; d_sdw_with_imm d0, r2, 0 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d1, r2, 1 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d2, r2, 2 }
; CHECK-NEXT:    { nop; nop; d_sdw_pre_imm d3, r2, 3 }
; CHECK-NEXT:    { addi32 r2, sp, 96; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 0 }
; CHECK-NEXT:    { addi32 r2, sp, 96; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 1 }
; CHECK-NEXT:    { addi32 r2, sp, 72; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 2 }
; CHECK-NEXT:    { addi32 r2, r0, -24; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 3 }
; CHECK-NEXT:    { addi32 r2, r0, -32; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, r1, 4 }
; CHECK-NEXT:    { s_lw_with_imm r0, r1, 0; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r0, r1, 0 }
; CHECK-NEXT:    { s_lw_with_imm r0, r1, 1; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r0, r1, 1 }
; CHECK-NEXT:    { s_lw_with_imm r0, r1, 2; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r0, r1, 2 }
; CHECK-NEXT:    { s_lw_with_imm r0, r1, 3; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r0, r1, 3 }
; CHECK-NEXT:    { s_lw_with_imm r0, r1, 4; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r0, r1, 4 }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 96; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
  %ap = alloca i8, i32 32, align 8
  call void @llvm.va_start(i8* %ap)
  call void @llvm.va_copy(i8* %ap, i8* %ap)
  call void @llvm.va_end(i8* %ap)
  ret void
}
declare void @llvm.va_start(i8*)
declare void @llvm.va_copy(i8*, i8*)
declare void @llvm.va_end(i8*)
