; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs  -enable-misched=false -enable-post-misched=false < %s | FileCheck %s

; Role: semantic — FILED : DR64 R_CMP instructions (SLT64 SEQ64, SLE64 and _S0/_S2 variants) have an operand-flag.

; REGRESSION FILED : DR64 R_CMP instructions (SLT64
; SEQ64, SLE64 and _S0/_S2 variants) have an operand-flag
; bug in HaydnFormatsALU64.td that aborts the MachineVerifier ("Explicit
; operand marked as def"). The.td marks operand 0 ($rd) as a def with
; hasSideEffects = 1 (implicit SFR write) — the verifier rejects this
; combination. Regressed in the Flex cutover. Selector is correct
; (MIR shows real emission); only the.td operand flags need adjusting.
; Track under / Flex cutover (DR64 R_CMP operand flags). Do NOT
; rebaseline CHECKs to silence the verifier abort.
;
; REGRESSION TEST: DR64 scalar compare and conditional move intrinsics.
;
; Purpose: Verify that 64-bit SFR compare (SLT64, SLE64, SEQ64) and
; conditional move (MOVT64, MOVF64) intrinsics emit the correct
; instructions. These intrinsics have IntrHasSideEffects because they
; interact with the SFR register.
;
; Why this test: The SFR compare/move intrinsics use a side-effect
; protocol: the compare writes SFR flags, and the move reads them.
; If hasSideEffects is incorrectly set (known bug #1: SFR writers with
; hasSideEffects=0 get eliminated as dead), the compare instruction
; gets DCE'd and the subsequent MOV reads stale SFR state. This test
; catches that regression by chaining compare→move in each function.
;
; Test design: Each function chains a compare intrinsic with a
; conditional move intrinsic, returning the move result. This forces
; both instructions to survive. If the compare is eliminated as dead
; the move will produce incorrect results and the CHECK lines will fail
; (or llc will crash with a verifier error).

;===----------------------------------------------------------------------===;
; SLT64 + MOVT64 chain
;===----------------------------------------------------------------------===;

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


declare i64 @llvm.haydn.slt64(i64, i64)
declare i64 @llvm.haydn.movt64(i64)

define dso_local i64 @test_slt64_movt64(i64 %a) {
; CHECK-LABEL: test_slt64_movt64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; slt64 d0, d0 }
; CHECK-NEXT:    { nop; nop; movt64 d0, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %cmp = call i64 @llvm.haydn.slt64(i64 %a, i64 %a)
  %r = call i64 @llvm.haydn.movt64(i64 %cmp)
  ret i64 %r
}

;===----------------------------------------------------------------------===;
; SLE64 + MOVF64 chain
;===----------------------------------------------------------------------===;

declare i64 @llvm.haydn.sle64(i64, i64)
declare i64 @llvm.haydn.movf64(i64)

define dso_local i64 @test_sle64_movf64(i64 %a) {
; CHECK-LABEL: test_sle64_movf64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; sle64 d0, d0 }
; CHECK-NEXT:    { nop; nop; movf64 d0, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %cmp = call i64 @llvm.haydn.sle64(i64 %a, i64 %a)
  %r = call i64 @llvm.haydn.movf64(i64 %cmp)
  ret i64 %r
}

;===----------------------------------------------------------------------===;
; SEQ64 standalone (sets SFR, returns passthrough)
;===----------------------------------------------------------------------===;

declare i64 @llvm.haydn.seq64(i64, i64)

define dso_local i64 @test_seq64(i64 %a) {
; CHECK-LABEL: test_seq64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; seq64 d0, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i64 @llvm.haydn.seq64(i64 %a, i64 %a)
  ret i64 %r
}

;===----------------------------------------------------------------------===;
; SFR register transfer: MOVESFR2GPR / MOVEGPR2SFR / ZERO_SFR
; These verify the SFR↔GPR32 transfer instructions survive codegen.
;===----------------------------------------------------------------------===;

declare i32 @llvm.haydn.movesfr2gpr()
declare void @llvm.haydn.movegpr2sfr(i32)
declare void @llvm.haydn.zero.sfr()

define dso_local i32 @test_movesfr2gpr() {
; CHECK-LABEL: test_movesfr2gpr:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; movesfr2gpr r1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i32 @llvm.haydn.movesfr2gpr()
  ret i32 %r
}

define dso_local void @test_movegpr2sfr(i32 %a) {
; CHECK-LABEL: test_movegpr2sfr:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; movegpr2sfr r1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  call void @llvm.haydn.movegpr2sfr(i32 %a)
  ret void
}

define dso_local void @test_zero_sfr() {
; CHECK-LABEL: test_zero_sfr:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; zero_sfr }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  call void @llvm.haydn.zero.sfr()
  ret void
}
