; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O1 -filetype=obj %s -o %t.o && \
; RUN:     llvm-objdump -d --triple=haydn-unknown-elf %t.o | FileCheck %s
; REQUIRES: haydn-registered-target

; Role: object — single-real-child bundles must objdump to the real mnemonic
; (ld32/add32), not a compressed c.* mis-decode or an all-nop parcel.


; Object contract: single-real-child bundles encode and disassemble to the
; real mnemonic (not c.* mis-decode, not a nop-only parcel). Do not weaken
; the CHECK / CHECK-NOT lines.
;
; REGRESSION TEST: single-real-child bundles must encode so llvm-objdump
; recovers the architectural mnemonic. Matches llvm-mc single-instruction
; bundle encoding for the same ops.
;
; Bug: HaydnMCCodeEmitter::encodeBundle packed EVERY non-empty bundle
; including single-instruction bundles like `{ ld32 r1, r1, 4; nop; nop }`
; into a 64-bit Mode-0 word (bits[3:0]=0011). The disassembler's 8-byte
; bundle probe (HaydnDisassembler::getInstruction) only accepts a Mode-0 word
; when decodeDClassBundle returns a BUNDLE-wrapped MCInst, and that helper
; returns a BARE instruction (no wrapper) when exactly ONE slot decodes. So
; single-child Mode-0 words were rejected by the probe and fell through to a
; legacy-flat scan that mis-decoded the bytes. Symptom in real codegen
; (coremark matrix_sum/matrix_add): `llvm-objdump -d` showed garbage like
; `c.add32 r8, r2` and `c.ldu16 r0, r0` instead of the real instruction.
;
; Example: `{ ld32 r1, r1, 4; nop; nop }` emitted by CodeGen as the Mode-0
; word 0x0000000000822243 (low nibble 0x3), which objdump rendered as
; `c.add32 r8, r2`. llvm-mc emits the same bundle as the standalone 32-bit
; G-format encoding of LD32 (`40 40 c4 4e`) + zero padding, which round-trips
; cleanly to `{ ld32 r1, r1, 4 }`.
;
; Fix : in encodeBundle, skip the Mode-0 packing path when the bundle
; has fewer than 2 real (non-NOP) children. Single-child bundles fall through
; to the legacy-flat encoder (encodeSingleInstruction per child + zero-pad to
; 8 bytes), producing the exact same bytes llvm-mc produces. Mode-0 packing
; is reserved for 2+ children, where decodeDClassBundle wraps the result in
; BUNDLE and the probe accepts it.
;
; Test design: minimal functions that produce single-instruction bundles
; (loads, stores, ALU ops with no parallelizable peer in the same packetize
; region). Each must disassemble to its REAL mnemonic — NOT a `c.*` compressed
; instruction (the tell-tale signature of the mis-decode). If the emitter
; regresses to Mode-0 packing for single-child bundles, these will render as
; `c.add32`, `c.sub32`, `c.ldu16`, etc.

@g1 = external global i32, align 4
@g2 = external global i32, align 4

; Single load in its own bundle (the second load has a different base, so the
; packetizer does not promote to LD32_S1 and pack them together). Each load
; ends up in a single-child bundle.
define i32 @single_load(i32 %a) nounwind {
; Post-R10 migration: the encoder uses Mode-0 bundles (one-child-per
; window) instead of 's legacy-flat path, but the load-bearing assertion
; is unchanged — single-child bundles decode to their REAL mnemonic, NOT
; garbage c.ld8/c.add32 compressed instructions. The CHECK-NOTs use {{^}}
; anchors so they only fire on a bare `c.add`/`c.ld` token at the start of
; the mnemonic (a `c.addi32 r0, 7` materialized by the spill path is a
; legitimate compressed immediate-add, not the c.add32 mis-decode this test
; guards against).
  %p = load i32, ptr @g1, align 4
  %r = add i32 %p, %a
  ret i32 %r
}

; Single ALU op between two loads (no parallel peer in the same region).
; The add32 lands in a single-child bundle.
define i32 @single_alu(i32 %a, i32 %b) nounwind {
  %r = add i32 %a, %b
  ret i32 %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
