; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s





;
; REGRESSION TEST: G_FCONSTANT soft-float constant materialization.
;
; Bug: HaydnLegalizerInfo listed G_FCONSTANT in the same
; `.libcallFor({S32, S64})` block as G_FADD/G_FMUL/... at the old line 226.
; A constant is not a runtime libcall, so the legalizer had no recipe for
; G_FCONSTANT and crashed:
; fatal error: unable to legalize instruction:
; %0:_(s32) = G_FCONSTANT float 2.500000e+00
; This blocked every IEEE-float kernel in M6 (all 62 `*f` files use float
; constants — every vec_addf/iirf/mathf kernel returns a float literal or
; compares against one).
;
; Fix: G_FCONSTANT is now `customFor({S32, S64})`. legalizeCustom bitcasts the
; float's APInt bit-pattern and emits `buildConstant(Dst, FVal.bitcastToAPInt)`
; into the float-typed destination vreg — the standard soft-float idiom
; (mirrors RISC-V's G_FCONSTANT handling). Haydn has no FPU, so every
; float value lives in a GPR/DR64 as its bit-cast integer.
;
; Test design: each function returns a distinct float/double constant. Before
; the fix, `llc` aborted with "unable to legalize instruction: G_FCONSTANT".
; After the fix, the bit-cast integer materialises via the integer constant
; path and the function compiles cleanly.
;
; f32 cases: the bit-pattern is upper-bits-only (low20 == 0), so a single
; 12-bit LUI reconstructs it: `lui rN, bits[31:20]` of the IEEE word. Each
; f32 CHECK pins that lui immediate — so it genuinely guards the bit-pattern
; reached the instruction stream, not just "llc didn't crash".
;
; f64 cases: the 64-bit bit-pattern is materialised as two 32-bit words stored
; to the stack and reloaded into a DR64 (`d_ldw_post_imm`). The CHECKs pin the
; hi32 word's lui immediate, which encodes the upper bits of the IEEE pattern
; and proves the bit-cast APInt reached the instruction stream.
;
; If G_FCONSTANT regresses back to libcallFor, llc crashes before emitting
; code and every CHECK fails.
;
; Reference: -softfloat-gfconstant-and-libcall-symbol.md
; RISCVLegalizerInfo.cpp case G_FCONSTANT

;f32 constant 2.5 (bit-pattern 0x40200000; bits[31:20] = 0x402 = 1026)


define float @ret_float_2p5() {
; CHECK-LABEL: ret_float_2p5:
; CHECK:       // #<spill-kpi> @ret_float_2p5 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { lui r1, 1026; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret float 2.500000e+00
}

;f32 constant 1.0 (bit-pattern 0x3f800000; bits[31:20] = 0x3f8 = 1016)
define float @ret_float_1p0() {
; CHECK-LABEL: ret_float_1p0:
; CHECK:       // #<spill-kpi> @ret_float_1p0 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { lui r1, 1016; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret float 1.000000e+00
}

;f32 constant 0.0 (bit-pattern 0x00000000) — soft-zero, uses R0
define float @ret_float_0p0() {
; CHECK-LABEL: ret_float_0p0:
; CHECK:       // #<spill-kpi> @ret_float_0p0 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { addi32 r1, r0, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret float 0.000000e+00
}

;f32 constant -2.0 (bit-pattern 0xc0000000; bits[31:20] = 0xc00 = 3072)
define float @ret_float_neg2p0() {
; CHECK-LABEL: ret_float_neg2p0:
; CHECK:       // #<spill-kpi> @ret_float_neg2p0 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { lui r1, 3072; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret float -2.000000e+00
}

;f64 constant 3.14 (bit-pattern 0x40091EB851EB851F)
; hi32 = 0x40091EB8 -> materialised as lui 0x401 (=1025) + addi32{{(_w)?}}; the
; lui immediate proves the upper IEEE bits reached the instruction stream.
define double @ret_double_3p14() {
; CHECK-LABEL: ret_double_3p14:
; CHECK:       // #<spill-kpi> @ret_double_3p14 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { lui r1, 1311; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; addi32 r1, r1, -293601 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, sp, 0 }
; CHECK-NEXT:    { lui r1, 1025; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, -450888; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, sp, 1 }
; CHECK-NEXT:    { d_ldw_with_imm d0, sp, 0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret double 3.140000e+00
}

;f64 constant 1.0 (bit-pattern 0x3ff0000000000000)
; hi32 = 0x3ff00000 -> single LUI 0x3ff (=1023).
define double @ret_double_1p0() {
; CHECK-LABEL: ret_double_1p0:
; CHECK:       // #<spill-kpi> @ret_double_1p0 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { subi32 sp, sp, 8; addi32 r1, r0, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, sp, 0 }
; CHECK-NEXT:    { lui r1, 1023; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 0; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, sp, 1 }
; CHECK-NEXT:    { d_ldw_with_imm d0, sp, 0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  ret double 1.000000e+00
}

;f32 constant used in arithmetic — exercises constant + libcall together.
; This is the minimal kernel shape that all M6 `*f` files share:
; a float literal feeding a float arithmetic op.
define float @const_plus_arg(float %a) {
; CHECK-LABEL: const_plus_arg:
; CHECK:       // #<spill-kpi> @const_plus_arg spills=1 spill-bytes=4 reloads=1 reload-bytes=4
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { lui r2, 1026; nop; nop }
; CHECK-NEXT:    { addi32 r2, r2, 0; nop }
; CHECK-NEXT:    { nop; jal lr, __addsf3; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = fadd float %a, 2.500000e+00
  ret float %r
}
