; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s






;
; Comprehensive tests for callee-saved register spill/restore.
;
; Callee-saved registers :
;   GPR: R8-R11           (R12 is reserved as the linker/assembler scratch "AT")
;   DR64: D8-D15
;   AR: AR2-AR3
;
; The prologue saves these to the stack and the epilogue restores them.
; Spills happen after SP decrement; restores happen before SP increment.
;
; Note: R13=SP, R14=FP, R15=LR are special-purpose. R14 is saved as
; callee-saved when FP is enabled. R0 is reserved as soft-zero.
;
; Note: The register allocator may use callee-saved registers to hold
; live values across calls, which triggers the prologue/epilogue to
; save/restore them. The specific registers used depend on RA decisions.
;
; Rebaselined for the Stream B post-RA MachineScheduler (decision)
; which was previously inert (createPostMachineScheduler returned nullptr)
; and is now active. It reorders instructions for ILP and the packetizer
; forms denser bundles, so the epilogue SP increment (addi32 sp, sp,...)
; may now be bundled earlier, interleaved with the callee-save restores.
; The frame/callee-save SEMANTICS is unchanged: the same callee-saved
; registers are spilled/restored at the same frame offsets, and the
; epilogue addi32 sp, sp, <size> is still present. CHECK lines below
; therefore use CHECK-DAG for prologue/epilogue pieces whose exact
; ordering is scheduler-dependent.



declare void @clobber_all()
declare i32 @use_i32(i32)
declare i64 @use_i64(i64)

;Leaf function: no callee saves needed (no calls)

define i32 @leaf_none(i32 %x) {
; CHECK-LABEL: leaf_none:
; CHECK:       // #<spill-kpi> @leaf_none spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { addi32 r1, r1, 1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = add i32 %x, 1
  ret i32 %r
}

;Single call: callee-save registers may be used to hold live values

define i32 @save_across_call(i32 %a) {
; CHECK-LABEL: save_across_call:
; CHECK:       // #<spill-kpi> @save_across_call spills=2 spill-bytes=8 reloads=2 reload-bytes=8
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { addi32 r2, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r2, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r2, 1 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r8, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { move32 r8, r1; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add32 r1, r1, r8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v = call i32 @use_i32(i32 %a)
  %r = add i32 %v, %a
  ret i32 %r
}

;Multiple GPR callee saves: force many registers to be live across calls

define i32 @save_many_gpr(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; Must spill callee-saved registers to hold 5 live values across calls
; Epilogue restores callee-saved registers and re-increments SP.
; Order is scheduler-dependent; verify each piece is present.
; CHECK-LABEL: save_many_gpr:
; CHECK:       // #<spill-kpi> @save_many_gpr spills=6 spill-bytes=24 reloads=6 reload-bytes=24
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 32; nop }
; CHECK-NEXT:    { addi32 r6, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r6, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm fp, r6, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r11, r6, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r6, 3 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r6, 4 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r6, 5 }
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset r8, 28
; CHECK-NEXT:    .cfi_offset r9, 24
; CHECK-NEXT:    .cfi_offset r10, 20
; CHECK-NEXT:    .cfi_offset r11, 16
; CHECK-NEXT:    .cfi_offset fp, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { move32 r8, r2; move32 r9, r3; nop }
; CHECK-NEXT:    { move32 r10, r4; move32 r11, r5; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 fp, r1; move32 r1, r8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r9; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r9, r1; move32 r1, r10; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r10, r1; move32 r1, r11; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { add32 r2, fp, r8; xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { add32 r2, r2, r9; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r10; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm fp, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r11, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 5; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 6; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 7; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 32; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v1 = call i32 @use_i32(i32 %a)
  %v2 = call i32 @use_i32(i32 %b)
  %v3 = call i32 @use_i32(i32 %c)
  %v4 = call i32 @use_i32(i32 %d)
  %v5 = call i32 @use_i32(i32 %e)
  %s1 = add i32 %v1, %v2
  %s2 = add i32 %s1, %v3
  %s3 = add i32 %s2, %v4
  %s4 = add i32 %s3, %v5
  ret i32 %s4
}

;DR64 callee saves: force DR64 registers to be saved

define i64 @save_dr64(i64 %a, i64 %b, i64 %c) {
; Must spill DR64 callee-saved registers
; Epilogue restores DR64 callee-saved registers and re-increments SP.
; Order is scheduler-dependent; verify each piece is present.
; CHECK-LABEL: save_dr64:
; CHECK:       // #<spill-kpi> @save_dr64 spills=4 spill-bytes=28 reloads=4 reload-bytes=28
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 9 }
; CHECK-NEXT:    { addi32 r1, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d10, r1, 0 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d9, r1, 1 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d8, r1, 2 }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset lr, 36
; CHECK-NEXT:    .cfi_offset d8, 24
; CHECK-NEXT:    .cfi_offset d9, 16
; CHECK-NEXT:    .cfi_offset d10, 8
; CHECK-NEXT:    { or64 d8, d1, d1; or64 d9, d2, d2; nop }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { or64 d10, d0, d0; or64 d0, d8, d8; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { or64 d8, d0, d0; or64 d0, d9, d9; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add64 d1, d10, d8; nop }
; CHECK-NEXT:    { add64 d0, d1, d0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d10, sp, 1; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d9, sp, 2; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d8, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 9; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v1 = call i64 @use_i64(i64 %a)
  %v2 = call i64 @use_i64(i64 %b)
  %v3 = call i64 @use_i64(i64 %c)
  %s1 = add i64 %v1, %v2
  %s2 = add i64 %s1, %v3
  ret i64 %s2
}

;Mixed GPR + DR64 callee saves

define i64 @save_mixed_gpr_dr64(i32 %a, i64 %b) {
; Both GPR and DR64 callee-save spills
; CHECK-LABEL: save_mixed_gpr_dr64:
; CHECK:       // #<spill-kpi> @save_mixed_gpr_dr64 spills=2 spill-bytes=12 reloads=2 reload-bytes=12
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 5 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d8, sp, 1 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset lr, 20
; CHECK-NEXT:    .cfi_offset d8, 8
; CHECK-NEXT:    { sext32t64 d8, r1; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add64 d0, d0, d8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d8, sp, 1; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %ext = sext i32 %a to i64
  %v = call i64 @use_i64(i64 %b)
  %r = add i64 %v, %ext
  ret i64 %r
}

;Clobber test: call to function that clobbers all caller-saved regs

define i32 @clobber_test(i32 %a, i32 %b) {
; GPR callee-saves must be preserved across the call
; CHECK-LABEL: clobber_test:
; CHECK:       // #<spill-kpi> @clobber_test spills=3 spill-bytes=12 reloads=3 reload-bytes=12
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32 r3, sp, 12; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r3, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r3, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r3, 2 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset r8, 20
; CHECK-NEXT:    .cfi_offset r9, 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r8, r1; move32 r9, r2; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_all; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add32 r1, r8, r9; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  call void @clobber_all()
  %r = add i32 %a, %b
  ret i32 %r
}

;Nested calls: callee-saves must survive multiple calls

define i32 @nested_calls(i32 %a) {
; Multiple calls, each potentially clobbering caller-saved regs
; CHECK-LABEL: nested_calls:
; CHECK:       // #<spill-kpi> @nested_calls spills=2 spill-bytes=8 reloads=2 reload-bytes=8
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { addi32 r2, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r2, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r2, 1 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r8, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 r8, r1; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add32 r1, r8, r1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 3; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v1 = call i32 @use_i32(i32 %a)
  %v2 = call i32 @use_i32(i32 %v1)
  %r = add i32 %v1, %v2
  ret i32 %r
}

;Deep register pressure: force many callee-saves with heavy computation

define i32 @deep_pressure(i32 %a0, i32 %a1, i32 %a2, i32 %a3,
; Must save callee-saved registers to hold live values across calls
; CHECK-LABEL: deep_pressure:
; CHECK:       // #<spill-kpi> @deep_pressure spills=8 spill-bytes=32 reloads=8 reload-bytes=32
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { addi32 r12, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r12, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm fp, r12, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r11, r12, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r12, 3 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r12, 4 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r12, 5 }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset r8, 36
; CHECK-NEXT:    .cfi_offset r9, 32
; CHECK-NEXT:    .cfi_offset r10, 28
; CHECK-NEXT:    .cfi_offset r11, 24
; CHECK-NEXT:    .cfi_offset fp, 20
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    { move32 r11, r2; move32 fp, r3; s_sw_with_imm r7, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { move32 r8, r4; move32 r9, r5; nop }
; CHECK-NEXT:    { move32 r10, r6; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; s_sw_with_imm r1, sp, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { move32 r1, r11; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r11, r1; move32 r1, fp; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 fp, r1; move32 r1, r8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r9; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r9, r1; move32 r1, r10; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { move32 r10, r1; s_lw_with_imm r1, sp, 3; nop } // 4-byte Folded Reload
; CHECK-NEXT:    // 4-byte Reload
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32; nop }
; CHECK-NEXT:    { s_lw_with_imm r2, sp, 2; xor32 r0, r0, r0; nop } // 4-byte Folded Reload
; CHECK-NEXT:    // 4-byte Reload
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r11; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, fp; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r8; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r9; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r10; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm fp, sp, 5; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r11, sp, 6; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 7; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 8; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 9; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
                          i32 %a4, i32 %a5, i32 %a6) {
  %v0 = call i32 @use_i32(i32 %a0)
  %v1 = call i32 @use_i32(i32 %a1)
  %v2 = call i32 @use_i32(i32 %a2)
  %v3 = call i32 @use_i32(i32 %a3)
  %v4 = call i32 @use_i32(i32 %a4)
  %v5 = call i32 @use_i32(i32 %a5)
  %v6 = call i32 @use_i32(i32 %a6)
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %s1, %v2
  %s3 = add i32 %s2, %v3
  %s4 = add i32 %s3, %v4
  %s5 = add i32 %s4, %v5
  %s6 = add i32 %s5, %v6
  ret i32 %s6
}

;DR64 deep pressure: force many DR64 callee-saves

define i64 @dr64_deep_pressure(i64 %a0, i64 %a1, i64 %a2) {
; CHECK-LABEL: dr64_deep_pressure:
; CHECK:       // #<spill-kpi> @dr64_deep_pressure spills=4 spill-bytes=28 reloads=4 reload-bytes=28
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 9 }
; CHECK-NEXT:    { addi32 r1, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d10, r1, 0 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d9, r1, 1 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d8, r1, 2 }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset lr, 36
; CHECK-NEXT:    .cfi_offset d8, 24
; CHECK-NEXT:    .cfi_offset d9, 16
; CHECK-NEXT:    .cfi_offset d10, 8
; CHECK-NEXT:    { or64 d8, d1, d1; or64 d9, d2, d2; nop }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { or64 d10, d0, d0; or64 d0, d8, d8; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { or64 d8, d0, d0; or64 d0, d9, d9; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; jal lr, use_i64; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add64 d1, d10, d8; nop }
; CHECK-NEXT:    { add64 d0, d1, d0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d10, sp, 1; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d9, sp, 2; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d8, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 9; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v0 = call i64 @use_i64(i64 %a0)
  %v1 = call i64 @use_i64(i64 %a1)
  %v2 = call i64 @use_i64(i64 %a2)
  %s1 = add i64 %v0, %v1
  %s2 = add i64 %s1, %v2
  ret i64 %s2
}
