; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Stack locals / calls: SP adjusts; returns via jalr_w; calls via jal_w.

; Stack locals / calls: SP adjusts; returns via jalr_w; calls via jal_w.

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped


declare void @use_ptr(ptr)
declare i32 @use_i32(i32)
declare i64 @use_i64(i64)

;Simple local variable (one i32 alloca)

define i32 @one_local(i32 %x) {
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; Stack allocation for local
; (SFR-strip) changed bundle layout (denser packing) — the SP restore may
; be hoisted above the local st32/ld32 (anti-dep); use CHECK-DAG. Rebaselined.
; NOTE: lone load may be promoted to ld32 (slot-1 over-promotion,); both
; ld32 and ld32 are semantically identical loads.
; CHECK-LABEL: one_local:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    { nop; addi32 r2, sp, 12 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r2, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p = alloca i32
  store i32 %x, ptr %p
  %v = load i32, ptr %p
  ret i32 %v
}

;Multiple local variables (3 i32 allocas)

define i32 @three_locals(i32 %a, i32 %b, i32 %c) {
; 3 x i32 = 12 bytes, rounded to 16 (8-byte alignment)
; Address calcs (r4/r5/r6 = SP+20/16/12) issue before the three stores;
; last store co-issues with the first reload (no intra-bundle RAW).
; CHECK-LABEL: three_locals:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; addi32 r4, sp, 20 }
; CHECK-NEXT:    { nop; addi32 r5, sp, 16 }
; CHECK-NEXT:    { nop; addi32 r6, sp, 12 }
; CHECK-NEXT:    { nop; st32 r1, r4, 0 }
; CHECK-NEXT:    { nop; st32 r2, r5, 0 }
; CHECK-NEXT:    { st32 r3, r6, 0; ld32 r1, r4, 0 }
; CHECK-NEXT:    { nop; ld32 r2, r5, 0 }
; CHECK-NEXT:    { nop; ld32 r3, r6, 0 }
; CHECK-NEXT:    { nop; add32 r1, r1, r2 }
; CHECK-NEXT:    { nop; add32 r1, r1, r3 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p1 = alloca i32
  %p2 = alloca i32
  %p3 = alloca i32
  store i32 %a, ptr %p1
  store i32 %b, ptr %p2
  store i32 %c, ptr %p3
  %v1 = load i32, ptr %p1
  %v2 = load i32, ptr %p2
  %v3 = load i32, ptr %p3
  %s = add i32 %v1, %v2
  %r = add i32 %s, %v3
  ret i32 %r
}

;Local with call (callee-save spill + local)

define i32 @local_with_call(i32 %a) {
; Stack for local + potential callee-save spills
; CHECK-LABEL: local_with_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, -4
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; jal lr, use_i32 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p = alloca i32
  store i32 %a, ptr %p
  %v = load i32, ptr %p
  %r = call i32 @use_i32(i32 %v)
  ret i32 %r
}

;Mixed i32 and i64 locals

define i64 @mixed_locals(i32 %a, i64 %b) {
; Both i32 and i64 allocas
; Dual LOADSTORE0 injectivity: st32 and d_sw_l_with_imm cannot share a cycle
; (both golden e0 LOADSTORE0 only). Address calcs stay sequential.
; CHECK-LABEL: mixed_locals:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 32 }
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    { nop; addi32 r2, sp, 28 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; addi32 r3, sp, 20 }
; CHECK-NEXT:    { nop; addi32 r1, r3, 4 }
; CHECK-NEXT:    { nop; ld32 r2, r2, 0 }
; CHECK-NEXT:    { nop; d_sw_l_with_imm d0, r3, 0 }
; CHECK-NEXT:    { nop; d_sw_h_with_imm d0, r1, 0 }
; CHECK-NEXT:    { nop; ld32 r3, r3, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { st32 r3, sp, 2; ld32 r1, r1, 0 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; st32 r1, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; sext32t64 d0, r2 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld64 d1, sp, 1 } // 8-byte Folded Reload
; CHECK-NEXT:    // 8-byte Reload
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; add64 d0, d0, d1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 32 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p32 = alloca i32
  %p64 = alloca i64
  store i32 %a, ptr %p32
  store i64 %b, ptr %p64
  %v32 = load i32, ptr %p32
  %v64 = load i64, ptr %p64
  %ext = sext i32 %v32 to i64
  %r = add i64 %ext, %v64
  ret i64 %r
}

;Array local: [4 x i32] = 16 bytes

define i32 @array_local(i32 %a) {
; (SFR-strip) changed bundle layout (denser packing) — SP restore hoisted; CHECK-DAG. Rebaselined.
; CHECK-LABEL: array_local:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r2, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %arr = alloca [4 x i32], align 8
  %p = getelementptr [4 x i32], ptr %arr, i32 0, i32 0
  store i32 %a, ptr %p
  %v = load i32, ptr %p
  ret i32 %v
}

;Stack frame with locals, callee-save spills, AND outgoing args

declare i32 @many_params(i32, i32, i32, i32, i32, i32, i32, i32, i32)

define i32 @full_frame(i32 %a) {
; Stack for: local + callee-save spills + outgoing stack arg
; CHECK-LABEL: full_frame:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 40 }
; CHECK-NEXT:    { nop; addi32 r2, sp, 32 }
; CHECK-NEXT:    { nop; st32 lr, r2, 0 }
; CHECK-NEXT:    { nop; st32 r8, r2, 1 }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    .cfi_offset lr, -8
; CHECK-NEXT:    { nop; addi32 r6, sp, 28 }
; CHECK-NEXT:    { st32 r1, r6, 0; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; addi32 r2, r0, 8 }
; CHECK-NEXT:    { nop; move32 r12, sp }
; CHECK-NEXT:    { nop; ld32 r1, r6, 0 }
; CHECK-NEXT:    { nop; s_sw_post_imm r2, r12, 2 }
; CHECK-NEXT:    { nop; addi32 r2, r0, 2 }
; CHECK-NEXT:    { nop; addi32 r3, r0, 3 }
; CHECK-NEXT:    { nop; addi32 r4, r0, 4 }
; CHECK-NEXT:    { nop; addi32 r5, r0, 5 }
; CHECK-NEXT:    { nop; addi32 r6, r0, 6 }
; CHECK-NEXT:    { nop; addi32 r7, r0, 7 }
; CHECK-NEXT:    { nop; addi32 r8, r0, 9 }
; CHECK-NEXT:    { nop; st32 r8, r12, 0 }
; CHECK-NEXT:    { nop; jal lr, many_params }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 8 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 9 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 40 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p = alloca i32
  store i32 %a, ptr %p
  %v = load i32, ptr %p
  %r = call i32 @many_params(i32 %v, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9)
  ret i32 %r
}

;Nested calls with parameter passing

define i32 @nested_call_chain(i32 %a, i32 %b) {
; First call result feeds into second call
; CHECK-LABEL: nested_call_chain:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; addi32 r3, sp, 12 }
; CHECK-NEXT:    { nop; st32 lr, r3, 0 }
; CHECK-NEXT:    { nop; st32 r9, r3, 1 }
; CHECK-NEXT:    { nop; st32 r8, r3, 2 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    .cfi_offset lr, -12
; CHECK-NEXT:    { nop; move32 r8, r2 }
; CHECK-NEXT:    { nop; jal lr, use_i32 }
; CHECK-NEXT:    { move32 r1, r8; move32 r9, r1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; jal lr, use_i32 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; add32 r1, r9, r1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; ld32 r9, sp, 4 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 5 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %v1 = call i32 @use_i32(i32 %a)
  %v2 = call i32 @use_i32(i32 %b)
  %r = add i32 %v1, %v2
  ret i32 %r
}

;Pointer to local stack variable passed to callee

define void @pass_stack_ptr(i32 %a) {
; CHECK-LABEL: pass_stack_ptr:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, -4
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; move32 r1, r2 }
; CHECK-NEXT:    { nop; jal lr, use_ptr }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p = alloca i32
  store i32 %a, ptr %p
  call void @use_ptr(ptr %p)
  ret void
}
