; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — s for leaf functions and prologue/epilogue decisions.

; Tests for leaf functions and prologue/epilogue decisions.
;
; Leaf functions do not call other functions, so they:
; Do not need callee-save spills
; May not need a stack frame at all (no allocas, no locals)
; Still zero R0 in the prologue (reserved soft-zero register)
;
; F24 (2026-08-15): epilogue XOR32 R0 re-zero is gated on
; hasCalls() || !CSI.empty(). Leaf no-call empty-CSI frames no longer
; emit a second xor32 before the return. Rebaselined: the CHECK-NEXT
; xor32 immediately before addi32-sp / jalr is the intended absence,
; not a missing restore. Caller-side re-zero stays HaydnExpandPseudos.
; @non_leaf still has the epilogue xor (hasCalls).

;Pure leaf: no stack frame at all

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define i32 @pure_leaf(i32 %x) {
; Only the R0 zeroing prologue, no SP adjustment
; CHECK-LABEL: pure_leaf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, 1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = add i32 %x, 1
  ret i32 %r
}

;Leaf with only arithmetic (no memory, no stack)

define i32 @leaf_arith(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: leaf_arith:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; add32 r2, r1, r2 }
; CHECK-NEXT:    { nop; mull r2, r2, r3 }
; CHECK-NEXT:    { nop; sub32 r1, r2, r1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
; 2026-08-21 latency P3 (golden Data_Latency=1 fresh-dest multiply): the
; mull -> sub32 consumer now issues in the NEXT parcel; the old all-NOP
; stall parcel is gone. Rebaselined; instruction stream is unchanged.
  %s1 = add i32 %a, %b
  %s2 = mul i32 %s1, %c
  %s3 = sub i32 %s2, %a
  ret i32 %s3
}

;Leaf with i64 arithmetic (no stack needed if only register ops)

define i64 @leaf_i64(i64 %a, i64 %b) {
; CHECK-LABEL: leaf_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop; add64 d0, d0, d1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = add i64 %a, %b
  ret i64 %r
}

;Leaf with comparison (no stack)

define i32 @leaf_cmp(i32 %a, i32 %b) {
; CHECK-LABEL: leaf_cmp:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; max32 r1, r1, r2 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %cmp = icmp sgt i32 %a, %b
  %r = select i1 %cmp, i32 %a, i32 %b
  ret i32 %r
}

;Non-leaf: function with a call (needs callee-save spills)

declare i32 @extern(i32)

define i32 @non_leaf(i32 %x) {
; Must save/restore callee-saved registers
; CHECK-LABEL: non_leaf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, -4
; CHECK-NEXT:    { nop; jal lr, extern }
; CHECK-NEXT:    { xor32 r0, r0, r0; addi32 r1, r1, 1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %v = call i32 @extern(i32 %x)
  %r = add i32 %v, 1
  ret i32 %r
}

;Leaf with alloca (needs stack frame but no callee saves)

define i32 @leaf_with_alloca(i32 %x) {
; Needs stack space for alloca
; (SFR-strip) changed bundle layout (denser packing) — the SP restore may
; be hoisted above the local st32/ld32 (anti-dep); use CHECK-DAG so the frame
; alloc/dealloc and local access are matched regardless of order. Rebaselined.
; CHECK-LABEL: leaf_with_alloca:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    { nop; addi32 r2, sp, 12 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; addi32 r1, r1, 1 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p = alloca i32
  store i32 %x, ptr %p
  %v = load i32, ptr %p
  %r = add i32 %v, 1
  ret i32 %r
}

;Leaf with multiple allocas

define i32 @leaf_multi_alloca(i32 %x) {
; CHECK-LABEL: leaf_multi_alloca:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    { addi32 r3, sp, 8; addi32 r2, sp, 12 }
; CHECK-NEXT:    { nop; st32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r2, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; st32 r1, r3, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld32 r1, r3, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %p1 = alloca i32
  %p2 = alloca i32
  store i32 %x, ptr %p1
  %v = load i32, ptr %p1
  store i32 %v, ptr %p2
  %r = load i32, ptr %p2
  ret i32 %r
}

;Void leaf function

define void @void_leaf() {
; CHECK-LABEL: void_leaf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret void
}

;Leaf with conditional branch (no stack needed)

define i32 @leaf_branch(i32 %a, i32 %b) {
; CHECK-LABEL: leaf_branch:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_remember_state
; CHECK-NEXT:    { nop; addi32 r3, r0, 0 }
; CHECK-NEXT:    { nop; slt32 r3, r3, r1 }
; CHECK-NEXT:    { nop; xori32 r3, r3, 1 }
; CHECK-NEXT:    { nop; bnez r3, .LBB8_2 }
; CHECK-NEXT:  // %bb.1: // %pos
; CHECK-NEXT:    { nop; add32 r1, r1, r2 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
; CHECK-NEXT:  .LBB8_2: // %neg
; CHECK-NEXT:    .cfi_restore_state
; CHECK-NEXT:    { nop; sub32 r1, r1, r2 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp sgt i32 %a, 0
  br i1 %cmp, label %pos, label %neg

pos:
  %r1 = add i32 %a, %b
  ret i32 %r1

neg:
  %r2 = sub i32 %a, %b
  ret i32 %r2
}
