; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 < %s | FileCheck %s

; Role: semantic — SET_HWLOOP must leave InterveningCycles=2 complete following parcels before BEGIN (SetupIssueDistance=3).

; REGRESSION: SET_HWLOOP must leave InterveningCycles=2 complete following
; parcels before BEGIN (SetupIssueDistance=3). Fixup inserts deficit
; NOPs when preheader work is short. MinSetupBytes = 2 × productParcel.

define void @hwloop_t3(ptr nocapture %p, i32 %n) {
; CHECK-LABEL: hwloop_t3:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r3, r0, 1; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 0; nop }
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    { st32_post r4, r1, 1; nop }
; CHECK-NEXT:    { add32 r4, r4, r3; nop }
; CHECK-NEXT:    { sltu32 r5, r4, r2; nop }
; CHECK-NEXT:    { bnez_w r5, .LBB0_1; nop }
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
entry:
  br label %loop
loop:
  %i = phi i32 [ 0, %entry ], [ %i2, %loop ]
  %gep = getelementptr inbounds i32, ptr %p, i32 %i
  store i32 %i, ptr %gep, align 4
  %i2 = add nuw i32 %i, 1
  %c = icmp ult i32 %i2, %n
  br i1 %c, label %loop, label %exit
exit:
  ret void
}
