; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 < %s | FileCheck %s

; Role: semantic — Single-BB ZOL: START/END labels must both be present; body has work.

; Single-BB ZOL: START/END labels must both be present; body has work.

define void @tiny_body(ptr nocapture %p, i32 %n) {
; CHECK-LABEL: tiny_body:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r3, r0, 0 }
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    { addi32 r3, r3, 1; s_sw_post_imm r3, r1, 1 }
; CHECK-NEXT:    { nop; sltu32 r4, r3, r2 }
; CHECK-NEXT:    { nop; bnez r4, .LBB0_1 }
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
; InterveningCycles=2 following parcels after SET before BEGIN.
; Inclusive START..END must both appear; body work lives between them.
entry:
  br label %loop
loop:
  %i = phi i32 [ 0, %entry ], [ %i2, %loop ]
  %gep = getelementptr inbounds i32, ptr %p, i32 %i
  store i32 %i, ptr %gep, align 4
  %i2 = add nuw i32 %i, 1
  %c = icmp ult i32 %i2, %n
  br i1 %c, label %loop, label %exit
exit:
  ret void
}
