; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs \
; RUN:   -mattr=+hwloop < %s | FileCheck %s

; Role: semantic — HiFi-competitive constant-trip loop: materialize count once, then ZOL.

; HiFi-competitive constant-trip loop: materialize count once, then ZOL.
; Haydn form: set_hwloop_f2_w with trip in a GPR (imm 10 loaded preheader).
;
; post-RA densify can move body ops without false failures. Core contract:
; 1) set_hwloop_f2 emitted (not silent drop / raw-text only)
; 2) start/end labels present (inclusive END on body)
; 3) soft back-edge gone


define i32 @hwloop_basic(ptr %p) {
; CHECK-LABEL: hwloop_basic:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { move32 r2, r1; nop }
; CHECK-NEXT:    { ld32 r2, r2, 0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 0; nop }
; CHECK-NEXT:    { addi32_w r3, r0, 1; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 10; nop }
; CHECK-NEXT:    { move32 r5, r1; nop }
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    { add32 r5, r5, r3; add32 r1, r1, r2 }
; CHECK-NEXT:    { sltu32 r6, r5, r4; nop }
; CHECK-NEXT:    { bnez_w r6, .LBB0_1; nop }
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %loop ]
  %val = load i32, ptr %p
  %sum.next = add i32 %sum, %val
  %i.next = add i32 %i, 1
  %cmp = icmp ult i32 %i.next, 10
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %sum.next
}
