; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s -o %t.s
; RUN: FileCheck %s --check-prefix=ASM < %t.s
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -filetype=obj < %s -o %t.o
; RUN: llvm-objdump -d %t.o | FileCheck %s --check-prefix=OBJDUMP
; REQUIRES: haydn-registered-target

; Role: object — destructive-constraint emitter error no longer fires — the selector now lowers wrap 32-bit mul via mull; full llc | llvm-mc | objdump round-trips.
; Objdump prints return as `jalr` (asm text may still show `jalr_w`).


;
; REBASELINED (post-/ Flex cutover, 2026-07): the slot-2 MAC
; destructive-constraint emitter error no longer fires — the selector now
; lowers wrap 32-bit mul via mull; full llc | llvm-mc | objdump round-trips.
;
; Exercises the full Haydn pipeline: LLVM IR -> GlobalISel -> VLIW packetizer
; > MC emission -> ELF object -> objdump disassembly.
;
; Specifically tests:
; GPR32 argument passing (7 args: R1-R7, 7th arg = ptr via R7)
; Struct field access via ld32/st32 with GEP offsets
; 32-bit wrap multiply (mull) — FIR coefficient multiplies
; 32-bit mul+add (mull + add32) — IIR sum-of-products
; 32-bit subtract (sub32) — feedback path
; State update stores (st32)
; Callee-saved register save/restore (R8-R11) using R12 as scratch
; Return value in R1
;
; REGRESSION TEST: R7 must NOT be used as the callee-save scratch register.
;
; Bug: The callee-save optimization previously used R7 (caller-saved/argument
; register) as a base pointer for consecutive callee-save stores. But R7 holds
; the 7th argument (ptr %state), which is live and used throughout the function
; body for loading/storing state values. Clobbering R7 caused all ld32/st32
; from %state to use a garbage base address.
;
; Fix: Use R12 as the scratch register instead. Since R12 is the reserved
; linker/assembler scratch ("AT"): never in the CSR list, so the stride-4
; optimization is always taken (the old R12NeedsSaving guard is always false).
; R7 (the state pointer) is now preserved across the prologue/epilogue, so
; state accesses work correctly.
;
; This test verifies that the state pointer in R7 is not clobbered by the
; callee-save prologue. If the scratch register regresses back to R7, the
; state loads/stores will use the wrong base and the CHECK lines below will
; fail because the instruction patterns change.
;=============================================================================;

; Simple biquad IIR in LLVM IR (no intrinsics, just standard IR)
; y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2] - a1*y[n-1] - a2*y[n-2]

define i32 @biquad_df1_simple(i32 %xn, i32 %b0, i32 %b1, i32 %b2, i32 %a1, i32 %a2, ptr %state) nounwind {
entry:
  ; Load state: {x[n-1], x[n-2], y[n-1], y[n-2]}
  %s0 = load i32, ptr %state
  %state1 = getelementptr i32, ptr %state, i32 1
  %s1 = load i32, ptr %state1
  %state2 = getelementptr i32, ptr %state, i32 2
  %s2 = load i32, ptr %state2
  %state3 = getelementptr i32, ptr %state, i32 3
  %s3 = load i32, ptr %state3

  ; Simplified: y = b0*xn + b1*x[n-1] + b2*x[n-2] - a1*y[n-1] - a2*y[n-2]
  ; Using 32-bit arithmetic (truncated, no fixed-point)
  %t0 = mul i32 %b0, %xn
  %t1 = mul i32 %b1, %s0
  %t2 = mul i32 %b2, %s1
  %t3 = mul i32 %a1, %s2
  %t4 = mul i32 %a2, %s3

  %sum0 = add i32 %t0, %t1
  %sum1 = add i32 %sum0, %t2
  %sum2 = sub i32 %sum1, %t3
  %yn = sub i32 %sum2, %t4

  ; Update state
  store i32 %xn, ptr %state
  store i32 %s0, ptr %state1
  store i32 %yn, ptr %state2
  store i32 %s2, ptr %state3

  ret i32 %yn
}

; === Assembly-level checks ===
; Verify that the assembly output contains the expected instruction mnemonics.
; We do NOT check exact registers or scheduling — only that the right
; instruction classes are selected by GlobalISel.

; ASM-LABEL: biquad_df1_simple:

; Prologue: stack frame setup and callee-save using R12 (not R7!)
; ASM: subi32{{.*}}sp, sp
; ASM: { {{.*}}addi32{{.*}}r12, sp, {{[0-9]+}}{{.*}} }
; Saved vars are R8-R11 only (R12 is reserved AT, never saved —).
; ASM: st32{{.*}}{{r[89]|r1[01]}}, r12

; Load state values from struct pointer via R7 (7th arg, preserved)
; ASM: ld32{{.*}}{{r[0-9]+|fp}}, r7, 0

; State update stores (still using R7 as base — the regression guard).
; Stores co-issue with mull before the subtracts, so DAG here — not after sub32.
; ASM-DAG: st32{{.*}}{{r[0-9]+|fp}}, r7,
; ASM-DAG: st32{{.*}}{{r[0-9]+|fp}}, r7,

; Coefficient multiplies (mull).
; ASM: mull
; ASM: mull
; ASM: mull

; Accumulation via add32 (the selector no longer emits mac32; the adds sum the
; per-tap products).
; ASM: add32

; Feedback subtraction
; ASM: sub32
; ASM: sub32

; Return value: the final sub32 leaves the result directly in r1 (no separate
; move needed). Epilogue returns via jalr_w.
; ASM: jalr{{.*}}r0, lr, 0

; === Objdump-level checks ===
; Verify the ELF object disassembles correctly, catching encoding/decoding bugs.
; REBASELINED (post-/): the full bundle now decodes cleanly — no
; <unknown> tokens. Objdump shows mull for wrap s32 mul.

; OBJDUMP-LABEL: <biquad_df1_simple>:

; OBJDUMP: subi32{{.*}}sp, sp
; OBJDUMP-DAG: mull
; OBJDUMP-DAG: mull
; OBJDUMP-DAG: mull
; OBJDUMP-DAG: sub32
; OBJDUMP-DAG: jalr{{.*}}r0, lr, 0
