; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — movda/movad lane pack/extract. T-DSP11 surface-truth pin.
;
; REGRESSION TEST: haydn_movda32x2 / two-live-GPR->DR64 pack is a memory
; round-trip, not a native register insert.
;
; Bug (T-DSP11 cost lie): the public intrinsic looks like a 1-op GPR->DR
; move. Golden Format E has MOVE32_DR_L/H (DR->GPR extract) but no
; GPR->DR lane-insert (ISA-63). Selector emits MOV_GPR_TO_DR64; two live
; GPR halves expand post-RA through the per-function DR64PackFI slot:
; ST32 lo, ST32 hi, LD64. One-half-R0 packs (movda32/movda16) stay
; stackless (sext32t64 + shift). If this regresses to a fake register
; insert, the ST32/LD64 CHECKs on test_movda32x2 fail; if the one-half
; path starts spilling, the sext32t64 CHECKs on test_movda32 fail.
;
; Test design: two live i32 args force the general pack; single-arg
; movda32/16 cover the R0-high stackless path; movad32 uses native
; move32_dr_{l,h}.

; Pack lo/hi GPR args into a DR64 via stack merge + ld64.

declare i64 @llvm.haydn.movda32(i32)

define i64 @test_movda32(i32 %x) {
; CHECK-LABEL: test_movda32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i64 @llvm.haydn.movda32(i32 %x)
  ret i64 %r
}

declare i64 @llvm.haydn.movda16(i32)

define i64 @test_movda16(i32 %x) {
; CHECK-LABEL: test_movda16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i64 @llvm.haydn.movda16(i32 %x)
  ret i64 %r
}

declare i64 @llvm.haydn.movda32x2(i32, i32)

define i64 @test_movda32x2(i32 %lo, i32 %hi) {
; CHECK-LABEL: test_movda32x2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; st32 r1, sp, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r2, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld64 d0, sp, 1 } // 8-byte Folded Reload
; CHECK-NEXT:    // 8-byte Reload
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i64 @llvm.haydn.movda32x2(i32 %lo, i32 %hi)
  ret i64 %r
}

declare i32 @llvm.haydn.movad32.low(i64)

define i32 @test_movad32_low(i64 %dr) {
; CHECK-LABEL: test_movad32_low:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; move32_dr_l r1, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i32 @llvm.haydn.movad32.low(i64 %dr)
  ret i32 %r
}

declare i32 @llvm.haydn.movad32.high(i64)

define i32 @test_movad32_high(i64 %dr) {
; CHECK-LABEL: test_movad32_high:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; move32_dr_h r1, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %r = call i32 @llvm.haydn.movad32.high(i64 %dr)
  ret i32 %r
}

define i32 @test_roundtrip_low(i32 %x) {
; CHECK-LABEL: test_roundtrip_low:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; move32_dr_l r1, d0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %dr = call i64 @llvm.haydn.movda32(i32 %x)
  %back = call i32 @llvm.haydn.movad32.low(i64 %dr)
  ret i32 %back
}
