; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs %s -o - | FileCheck %s

; Role: semantic — large constant materialization (constants that don't fit in simm16).

; Test large constant materialization (constants that don't fit in simm16).
; ISA-43 #1 / : LUI is 12-bit (sets bits[31:20]); the materialiser uses
; ORI32 from R0 for uimm16, ADDI32 for simm16, and the 2-instruction
; `lui hi12` + `addi32{{(_w)?}} simm20` pair for every other case (the 12+20 split
; covers the whole 32-bit space; canonical pair post-ASO-removal).
; Every sequence below verified by reconstructing the
; value from R0: hi12 = (V + 0x80000) >> 20, simm20 = V - (hi12 << 20).

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define i32 @test_large_positive() {
; 0x10000: fits in simm20 -> single addi32{{(_w)?}} from R0.
; CHECK-LABEL: test_large_positive:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 65536 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 65536
}

define i32 @test_large_negative() {
; 0xFFFF0000 = -65536: fits in simm20 -> single addi32{{(_w)?}} from R0.
; CHECK-LABEL: test_large_negative:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, -65536 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -65536
}

define i32 @test_max_positive() {
; 0x7FFFFFFF: lui 0x800 (=0x80000000); addi32{{(_w)?}} -1 -> 0x7FFFFFFF.
; CHECK-LABEL: test_max_positive:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 2048 }
; CHECK-NEXT:    { nop; addi32 r1, r1, -1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 2147483647
}

define i32 @test_min_negative() {
; 0x80000000: single LUI 0x800.
; CHECK-LABEL: test_min_negative:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 2048 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -2147483648
}

define i32 @test_bit_pattern() {
; 0x92461840: round-trips through (2340<<20 + 0x61840) -> 2-instruction pair.
; CHECK-LABEL: test_bit_pattern:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; lui r1, 2340 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 399424 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 2454067264
}

define i32 @test_small_positive() {
; CHECK-LABEL: test_small_positive:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 100 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 100
}

define i32 @test_small_negative() {
; CHECK-LABEL: test_small_negative:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, -100 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 -100
}

define i32 @test_zero() {
; CHECK-LABEL: test_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i32 0
}

define i32 @test_add_with_large() {
; 65536 + 42 = 65578 = 0x1002A: fits in simm20 -> single addi32{{(_w)?}} from R0.
; CHECK-LABEL: test_add_with_large:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 65578 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %1 = add i32 65536, 42
  ret i32 %1
}

define i32 @test_pointer_constant(i32 %a) {
; 0x10000 used in arithmetic: single addi32{{(_w)?}} from R0 (simm20), then add32.
; CHECK-LABEL: test_pointer_constant:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r1, 65536 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  %2 = add i32 %a, 65536
  ret i32 %2
}
