; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 < %s | FileCheck %s

; Role: semantic — Two independent i64 loads: expect 64-bit load forms (ld64 / d_ldw_*), not two slot-1-only conflicts that force separate issue.

; Two independent i64 loads: expect 64-bit load forms (ld64 / d_ldw_*),
; not two slot-1-only conflicts that force separate issue.

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define void @dual_load_i64(ptr %a, ptr %b) {
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; CHECK-LABEL: dual_load_i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; d_ldw_post_imm d0, r1, 1 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; ld64 d1, r1, 0 }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { nop; nop; add64 d0, d0, d1 }
; CHECK-NEXT:    { nop; st64 d0, r2, 0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa sp, 0
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %x = load i64, ptr %a, align 8
  %ap = getelementptr i64, ptr %a, i32 1
  %y = load i64, ptr %ap, align 8
  %s = add i64 %x, %y
  store i64 %s, ptr %b, align 8
  ret void
}
