; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs \
; RUN:     < %s 2>&1 | FileCheck %s

; Role: semantic — i64 constant materialization must use the rematerializable LOADI64 pseudo, NOT the MatInt-halves + MOV_GPR_TO_DR64 chain.

; REGRESSION TEST: i64 constant materialization must use the rematerializable
; LOADI64 pseudo, NOT the MatInt-halves + MOV_GPR_TO_DR64 chain.
;
; Bug : the old chain (lo32/hi32 HaydnMatInt into GPR32 vregs + a
; MOV_GPR_TO_DR64 merge) was a 3+-instruction sequence with virtual-register
; operands, so RA could not rematerialize it. When an i64 constant was used in
; a non-dominating join block, RA cross-block-copied the DR64 result via
; `OR64 %x, %x`, referencing the single materialization that did not dominate
; the use -> "Virtual register defs don't dominate all uses" verifier abort.
;
; Fix: the selector emits one LOADI64 pseudo (single i64 immediate operand
; isReMaterializable). RA rematerializes it at each use; expandPostRAPseudo
; lowers it (MatInt lo/hi into a scavenged post-RA GPR scratch + a transient
; SP slot + LD64 — not fixed R12/AT). This test's -verify-machineinstrs is
; the probe: if the old dominance bug returns, llc aborts and FileCheck sees
; no output.

; Post-RA expansion of rematerializable LOADI64: MatInt into a scavenged GPR
; + transient SP slot + ld64 into the DR64 result (not a live OR64 copy).
; Two-block use of the same constant must still verify (no non-dominating
; OR64 copy of a single materialization).

define i64 @i64_const_small() nounwind {
; CHECK-LABEL: i64_const_small:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; addi32 r1, r0, 1 }
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i64 1
}

define i64 @i64_const_large() nounwind {
; CHECK-LABEL: i64_const_large:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; lui r1, 291 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 284280 }
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i64 305419896            ; 0x12345678
}

define i64 @i64_const_neg() nounwind {
; CHECK-LABEL: i64_const_neg:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; addi32 r1, r0, -1 }
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
  ret i64 -1                   ; 0xFFFFFFFFFFFFFFFF
}

define i64 @i64_const_in_two_blocks(i32 %c) nounwind {
; CHECK-LABEL: i64_const_in_two_blocks:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; addi32 r1, r0, 42 }
; CHECK-NEXT:    { nop; sext32t64 d0, r1 }
; CHECK-NEXT:    { nop; slli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; srli64 d0, d0, 32 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %t = icmp eq i32 %c, 0
  br i1 %t, label %then, label %else
then:
  ret i64 42
else:
  ret i64 42
}
