; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 < %s | FileCheck %s
;
; G_MUL s32 → MULL (golden MAC GRR). CHECK-NOT phantom mul32 / libcall.



define i32 @scalar_mul(i32 %a, i32 %b) {
; CHECK-LABEL: scalar_mul:
; CHECK:       // #<spill-kpi> @scalar_mul spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { mull r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
  %m = mul i32 %a, %b
  ret i32 %m
}

; Conditional multiply (shape: `if (n & 1) h = h * x;`).
define i32 @cond_mul(i32 %n, i32 %h, i32 %x) {
; CHECK-LABEL: cond_mul:
; CHECK:       // #<spill-kpi> @cond_mul spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { andi32 r1, r1, 1; addi32 r4, r0, 0 }
; CHECK-NEXT:    { mull r3, r2, r3; seq32 r1, r1, r4; nop }
; CHECK-NEXT:    { movt32 r3, r2, r1; nop; nop }
; CHECK-NEXT:    { move32 r1, r3; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
  %bit = and i32 %n, 1
  %cmp = icmp eq i32 %bit, 0
  %mh = mul i32 %h, %x
  %sel = select i1 %cmp, i32 %h, i32 %mh
  ret i32 %sel
}
