; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — PEI epilogue must not use R1 as the CSR-restore offset scratch.


;
; PEI epilogue must not use R1 as the CSR-restore offset scratch.
;
; Integer return values live in R1 across the epilogue. Offsets that do not
; fit golden scaled-simm6 CSR loads are materialized into a PEI scratch via
; xor+addi (emitCSRLoad). If that scratch is R1, the return value is replaced
; by the last restore offset (BundleSim cb44: guest_exit=196).
;
; Force large stack + GPR CSRs live across a call → REG-offset restores.
; Fixed: offset materialize uses a non-r1 scratch (typically r2).

declare void @ext(ptr)

; Large frame forces reg-offset CSR restores.
; Return sum is computed into r1 before the epilogue restore sequence.
; Epilogue materializes large restore offsets without clobbering r1.
; Current lowering uses soft-zero r0 as the offset scratch + ld32_reg.

define i32 @ret_after_csr_epilogue(i32 %x) {
; CHECK-LABEL: ret_after_csr_epilogue:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 224; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 200; nop }
; CHECK-NEXT:    { st32 lr, r2, 0; nop }
; CHECK-NEXT:    { st32 fp, r2, 1; nop }
; CHECK-NEXT:    { st32 r11, r2, 2; nop }
; CHECK-NEXT:    { st32 r10, r2, 3; nop }
; CHECK-NEXT:    { st32 r9, r2, 4; nop }
; CHECK-NEXT:    { st32 r8, r2, 5; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 224
; CHECK-NEXT:    .cfi_offset r8, 220
; CHECK-NEXT:    .cfi_offset r9, 216
; CHECK-NEXT:    .cfi_offset r10, 212
; CHECK-NEXT:    .cfi_offset r11, 208
; CHECK-NEXT:    .cfi_offset fp, 204
; CHECK-NEXT:    .cfi_offset lr, 200
; CHECK-NEXT:    { addi32_w r8, sp, 8; nop }
; CHECK-NEXT:    { move32 r9, r1; move32 r1, r8 }
; CHECK-NEXT:    { addi32_w r10, r0, 1; nop }
; CHECK-NEXT:    { addi32_w r11, r0, 2; nop }
; CHECK-NEXT:    { addi32_w fp, r0, 3; nop }
; CHECK-NEXT:    { jal_w lr, ext; nop }
; CHECK-NEXT:    { add32 r1, r9, r10; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { st32 r1, r8, 0; nop }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { add32 r1, r9, r11; nop }
; CHECK-NEXT:    { st32 r1, r8, 10; nop }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { add32 r1, r9, fp; nop }
; CHECK-NEXT:    { st32 r1, r8, 20; nop }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 4; nop }
; CHECK-NEXT:    { add32 r1, r9, r1; nop }
; CHECK-NEXT:    { st32 r1, r8, 30; nop }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { move32 r1, r8; nop }
; CHECK-NEXT:    { jal_w lr, ext; nop }
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { ld32 r1, r8, 0; nop }
; CHECK-NEXT:    { ld32 r2, r8, 10; nop }
; CHECK-NEXT:    { ld32 r3, r8, 20; nop }
; CHECK-NEXT:    { ld32 r4, r8, 30; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { add32 r1, r1, r2; nop }
; CHECK-NEXT:    { add32 r2, r3, r4; nop }
; CHECK-NEXT:    { add32 r1, r1, r2; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 200; nop }
; CHECK-NEXT:    { ld32_reg lr, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 204; nop }
; CHECK-NEXT:    { ld32_reg fp, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 208; nop }
; CHECK-NEXT:    { ld32_reg r11, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 212; nop }
; CHECK-NEXT:    { ld32_reg r10, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 216; nop }
; CHECK-NEXT:    { ld32_reg r9, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 220; nop }
; CHECK-NEXT:    { ld32_reg r8, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 224; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
entry:
  %buf = alloca [48 x i32], align 4
  call void @ext(ptr %buf)
  %a = add i32 %x, 1
  %b = add i32 %x, 2
  %c = add i32 %x, 3
  %d = add i32 %x, 4
  store i32 %a, ptr %buf
  %p1 = getelementptr [48 x i32], ptr %buf, i32 0, i32 10
  store i32 %b, ptr %p1
  %p2 = getelementptr [48 x i32], ptr %buf, i32 0, i32 20
  store i32 %c, ptr %p2
  %p3 = getelementptr [48 x i32], ptr %buf, i32 0, i32 30
  store i32 %d, ptr %p3
  call void @ext(ptr %buf)
  %v0 = load i32, ptr %buf
  %v1 = load i32, ptr %p1
  %v2 = load i32, ptr %p2
  %v3 = load i32, ptr %p3
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %v2, %v3
  %s = add i32 %s1, %s2
  ret i32 %s
}
