; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — End-to-end tests for pre-legalizer combiner optimizations.

; End-to-end tests for pre-legalizer combiner optimizations.
; These functions verify that the combiner correctly simplifies patterns
; before the legalizer runs.

; Test: sext i16 -> i32 should produce a shift-based sign extension.
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (setDesc members; AIEBaseAsmPrinter field order); .file skipped


define i32 @test_sext_i16(i16 %x) {
; CHECK-LABEL: test_sext_i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; slli32 r1, r1, 16 }
; CHECK-NEXT:    { nop; srai32 r1, r1, 16 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
  %ext = sext i16 %x to i32
  ret i32 %ext
}

; Test: constant folding should reduce add of two constants.
define i32 @test_const_fold() {
; CHECK-LABEL: test_const_fold:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; addi32 r1, r0, 142 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
entry:
  ret i32 142
}

; Test: shift by zero is eliminated (result is just the input).
define i32 @test_shift_zero(i32 %x) {
; CHECK-LABEL: test_shift_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
  %result = shl i32 %x, 0
  ret i32 %result
}

; Test: AND with all-ones is identity.
define i32 @test_and_all_ones(i32 %x) {
; CHECK-LABEL: test_and_all_ones:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
  %result = and i32 %x, -1
  ret i32 %result
}

; Test: OR with zero is identity.
define i32 @test_or_zero(i32 %x) {
; CHECK-LABEL: test_or_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; subi32 sp, sp, 8 }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 8 }
; CHECK:    { nop; jalr r0, lr, 0 }
  %result = or i32 %x, 0
  ret i32 %result
}
