; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; 2026-08-22 hwloop product-default flip rebaseline: default now ON (loops form LoopStart/PseudoLoopEnd); output regenerated to pin the NEW default.
; RUN:   -stop-before=greedy -verify-machineinstrs < %s -o - \
; RUN:   | FileCheck %s --check-prefix=PREGREEDY
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; RUN:   -stop-before=postmisched -verify-machineinstrs < %s -o - \
; RUN:   | FileCheck %s --check-prefix=PREPOST
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; RUN:   -stop-after=postmisched -verify-machineinstrs < %s -o - \
; RUN:   | FileCheck %s --check-prefix=POST
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; RUN:   -stats -verify-machineinstrs < %s -o /dev/null 2>&1 \
; RUN:   | FileCheck %s --check-prefix=STATS
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; RUN:   -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=ASM

; Role: MIR — soft-exit pre-RA QoR corpus (RecMII/II floors + post-RA
; exact-pack correlation; no durable cycle invent before handoff).

; Pre-RA soft-exit QoR slice. Owns list-sched + CreateTargetMIHazardRecognizer
; (IsPreRA) + PortModel floors + matching-frontier tryCandidate. Does not own
; SMS ResourceCycle / analyzeLoop / MachinePipeliner hooks (sibling:
; sms-format-qor-exit / sms-format-resmii*).
;
; Contracts:
; 1. -stop-before=greedy: pre-RA list-sched emits only logical opcodes — no
;    private member setDesc (_S0/_S1/_S2), no FormatID stamp, no durable BUNDLE
;    roots invented from matching-frontier scores (phase identity).
; 2. -stop-before=postmisched: through RA the same kernels stay logical — still
;    no pre-handoff hard BUNDLE (handoff metrics-only freeze).
; 3. -stop-after=postmisched: post-RA exact no-split owns multi-MI BUNDLE {{[01]}}
;    commit for packable independent sets (pre-RA only proved packability via
;    productQualKernel* oracles; unit: PreRASoftExitQoRFloorsAndExactPack).
; 4. -stats: multi-MI exact finalize > 0; scheduled split + unstamped hard-root
;    counters stay silent (zero).
; 5. II / Res floors (pre-RA surface): port ResMII binds when format-only is 1
;    (3×1W GPR writes → soft-exit II floor ≥ 2 via productSoftExitIIFloor). Rec
;    floors for loop-carried MAC acc feedback remain SMS/DDG (macc-acc-feedback);
;    pre-RA does not invent RecMII.
; 6. Pressure / critical path stay primary under matching-frontier ranking
;    (scheduler-ilp.ll / scheduler-critical-path.ll peers).
;
; Companion unit: HaydnPortModelTest.PreRASoftExitQoRFloorsAndExactPack
; Companion MIR: prera-format-feasibility.mir (vreg ports / three-ready rematch)
; Dual-run generic-pass baseline (VF3-G2): prera-format-generic-baseline.ll

target datalayout = "e-m:e-p:32:32-i64:32-f64:32-v64:32-v128:64-a:0:32-n32-S64"
target triple = "haydn-unknown-elf"

; Independent ALU triple — pre-RA logical only; post-RA may exact-commit a
; multi-MI Full cycle (ports may pack 2-wide under 4R2W). Soft-exit II floor
; unit-pins max(format=1, port for full 3×2R1W=2) without inventing HANDOFF.
define i32 @qor_pack_three_alu(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e, i32 %f) {
; ASM-LABEL: qor_pack_three_alu:
; ASM:       // %bb.0: // %entry
; ASM-NEXT:    { nop; xor32 r0, r0, r0 }
; ASM-NEXT:    { nop; subi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa_offset 8
; ASM-NEXT:    { nop; xor32 r2, r3, r4; add32 r1, r1, r2 }
; ASM-NEXT:    { nop; add32 r1, r1, r2; or32 r3, r5, r6 }
; ASM-NEXT:    { nop; add32 r1, r1, r3 }
; ASM-NEXT:    { nop; addi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa sp, 0
; ASM-NEXT:    { nop; jalr r0, lr, 0 }
; PREGREEDY-LABEL: name: qor_pack_three_alu
; PREGREEDY: bb.0.entry:
; PREGREEDY-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $r2
; PREGREEDY-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $r3
; PREGREEDY-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $r4
; PREGREEDY-NEXT:   [[COPY3:%[0-9]+]]:gpr32 = COPY $r5
; PREGREEDY-NEXT:   [[COPY4:%[0-9]+]]:gpr32 = COPY $r6
; PREGREEDY-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY $r1
; PREGREEDY-NEXT:   [[ADD32_:%[0-9]+]]:gpr32 = ADD32 [[COPY5]], [[COPY]]
; PREGREEDY-NEXT:   [[XOR32_:%[0-9]+]]:gpr32 = XOR32 [[COPY1]], [[COPY2]]
; PREGREEDY-NEXT:   [[OR32_:%[0-9]+]]:gpr32 = OR32 [[COPY3]], [[COPY4]]
; PREGREEDY-NEXT:   [[ADD32_1:%[0-9]+]]:gpr32 = ADD32 [[ADD32_]], [[XOR32_]]
; PREGREEDY-NEXT:   [[ADD32_2:%[0-9]+]]:gpr32 = ADD32 [[ADD32_1]], [[OR32_]]
; PREGREEDY-NEXT:   $r1 = COPY [[ADD32_2]]
; PREGREEDY-NEXT:   RET implicit $r15, implicit $r1, implicit $r15
;
; PREPOST-LABEL: name: qor_pack_three_alu
; PREPOST: bb.0.entry:
; PREPOST-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r0
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; PREPOST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; PREPOST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r2
; PREPOST-NEXT:   $r2 = XOR32 killed $r3, killed $r4
; PREPOST-NEXT:   $r3 = OR32 killed $r5, killed $r6
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r2
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r3
; PREPOST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; PREPOST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; PREPOST-NEXT:   $r0 = JALR_W $r15, 0, implicit $r1
;
; POST-LABEL: name: qor_pack_three_alu
; POST: bb.0.entry:
; POST-NEXT:   liveins: $r1, $r2, $r3, $r4, $r5, $r6, $r0
; POST-NEXT: {{  $}}
; POST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; POST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; POST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; POST-NEXT:   BUNDLE 1, 0, implicit-def $r1, implicit-def $r2, implicit killed $r1, implicit killed $r2, implicit killed $r3, implicit killed $r4 {
; POST-NEXT:     $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r2
; POST-NEXT:     $r2 = XOR32_E3_E1_ALU1_RR killed $r3, killed $r4
; POST-NEXT:   }
; POST-NEXT:   BUNDLE 1, 0, implicit-def $r3, implicit-def $r1, implicit killed $r5, implicit killed $r6, implicit killed $r1, implicit killed $r2 {
; POST-NEXT:     $r3 = OR32_E3_E2_ALU2_RR killed $r5, killed $r6
; POST-NEXT:     $r1 = ADD32_E3_E1_ALU1_RR killed $r1, killed $r2
; POST-NEXT:   }
; POST-NEXT:   $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r3
; POST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; POST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; POST-NEXT:   $r0 = JALR_W $r15, 0, implicit killed $r1
entry:
  %x = add i32 %a, %b
  %y = xor i32 %c, %d
  %z = or i32 %e, %f
  %t0 = add i32 %x, %y
  %t1 = add i32 %t0, %z
  ret i32 %t1
}

; Port-forced II floor body: three independent live results from three
; distinct memory sources (defeats IR fold of a+10/a+20/a+30 → 3a+60).
; Pre-RA HR (IsPreRA + PortModel) charges multi-cycle under 2W for dense
; write sets — still logical-only at stop-before greedy/postmisched. Unit:
; productSoftExitIIFloor({ADD32×3}, GPRW=3) == 2
; (HaydnPortModelTest.PreRASoftExitQoRFloorsAndExactPack).
define i32 @qor_three_write_port_floor(ptr nocapture readonly %p,
; ASM-LABEL: qor_three_write_port_floor:
; ASM:       // %bb.0: // %entry
; ASM-NEXT:    { nop; xor32 r0, r0, r0 }
; ASM-NEXT:    { nop; subi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa_offset 8
; ASM-NEXT:    { ld32 r2, r2, 0; ld32 r1, r1, 0 }
; ASM-NEXT:    { nop; ld32 r3, r3, 0 }
; ASM-NEXT:    { nop; add32 r1, r1, r2 }
; ASM-NEXT:    { nop; add32 r1, r1, r3 }
; ASM-NEXT:    { nop; addi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa sp, 0
; ASM-NEXT:    { nop; jalr r0, lr, 0 }
; PREGREEDY-LABEL: name: qor_three_write_port_floor
; PREGREEDY: bb.0.entry:
; PREGREEDY-NEXT:   liveins: $r1, $r2, $r3
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $r2
; PREGREEDY-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $r3
; PREGREEDY-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $r1
; PREGREEDY-NEXT:   [[LD32_:%[0-9]+]]:gpr32 = LD32 [[COPY2]], 0 :: (load (s32) from %ir.p)
; PREGREEDY-NEXT:   [[LD32_1:%[0-9]+]]:gpr32 = LD32 [[COPY]], 0 :: (load (s32) from %ir.q)
; PREGREEDY-NEXT:   [[LD32_2:%[0-9]+]]:gpr32 = LD32 [[COPY1]], 0 :: (load (s32) from %ir.r)
; PREGREEDY-NEXT:   [[ADD32_:%[0-9]+]]:gpr32 = ADD32 [[LD32_]], [[LD32_1]]
; PREGREEDY-NEXT:   [[ADD32_1:%[0-9]+]]:gpr32 = ADD32 [[ADD32_]], [[LD32_2]]
; PREGREEDY-NEXT:   $r1 = COPY [[ADD32_1]]
; PREGREEDY-NEXT:   RET implicit $r15, implicit $r1, implicit $r15
;
; PREPOST-LABEL: name: qor_three_write_port_floor
; PREPOST: bb.0.entry:
; PREPOST-NEXT:   liveins: $r1, $r2, $r3, $r0
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; PREPOST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; PREPOST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; PREPOST-NEXT:   $r1 = LD32 killed $r1, 0 :: (load (s32) from %ir.p)
; PREPOST-NEXT:   $r2 = LD32 killed $r2, 0 :: (load (s32) from %ir.q)
; PREPOST-NEXT:   $r3 = LD32 killed $r3, 0 :: (load (s32) from %ir.r)
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r2
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r3
; PREPOST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; PREPOST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; PREPOST-NEXT:   $r0 = JALR_W $r15, 0, implicit $r1
;
; POST-LABEL: name: qor_three_write_port_floor
; POST: bb.0.entry:
; POST-NEXT:   liveins: $r1, $r2, $r3, $r0
; POST-NEXT: {{  $}}
; POST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; POST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; POST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; POST-NEXT:   BUNDLE 0, 0, implicit-def $r1, implicit-def $r2, implicit killed $r1, implicit killed $r2 :: (load (s32) from %ir.p), (load (s32) from %ir.q) {
; POST-NEXT:     $r1 = S_LW_WITH_IMM_E2_E1_LOAD1_RI6 killed $r1, 0 :: (load (s32) from %ir.p)
; POST-NEXT:     $r2 = S_LW_WITH_IMM_E2_E0_LOADSTORE0_RI6 killed $r2, 0 :: (load (s32) from %ir.q)
; POST-NEXT:   }
; POST-NEXT:   $r3 = S_LW_WITH_IMM_E2_E1_LOAD1_RI6 killed $r3, 0 :: (load (s32) from %ir.r)
; POST-NEXT:   $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r2
; POST-NEXT:   $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r3
; POST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; POST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; POST-NEXT:   $r0 = JALR_W $r15, 0, implicit killed $r1
                                       ptr nocapture readonly %q,
                                       ptr nocapture readonly %r) {
entry:
  %x = load i32, ptr %p, align 4
  %y = load i32, ptr %q, align 4
  %z = load i32, ptr %r, align 4
  %t0 = add i32 %x, %y
  %t1 = add i32 %t0, %z
  ret i32 %t1
}

; Streaming dual-load MAC-shaped kernel — pre-RA through RA stays logical
; (no HANDOFF invent). Post-RA exact-pack owns BUNDLE. RecMII for acc feedback
; is SMS-owned (macc-acc-feedback / sms-format-qor-exit); here pin only that
; pre-RA list + RA never stamp members or invent cycle groups.
define i32 @qor_dual_load_mac_stream(ptr nocapture readonly %x,
; ASM-LABEL: qor_dual_load_mac_stream:
; ASM:       // %bb.0: // %entry
; ASM-NEXT:    { nop; xor32 r0, r0, r0 }
; ASM-NEXT:    { nop; subi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa_offset 8
; ASM-NEXT:    { nop; move32 r4, r1 }
; ASM-NEXT:    { nop; addi32 r1, r0, 0 }
; ASM-NEXT:    { nop; slt32 r5, r1, r3 }
; ASM-NEXT:    { nop; xori32 r5, r5, 1 }
; ASM-NEXT:    { nop; bnez r5, .LBB2_3 }
; ASM-NEXT:  // %bb.1: // %loop.preheader
; ASM-NEXT:    { nop; set_hwloop_f2 0, .LLhwloop_start0, .LLhwloop_end0, r3 }
; ASM-NEXT:    { nop; nop }
; ASM-NEXT:    { nop; nop }
; ASM-NEXT:  .LBB2_2: // %loop
; ASM-NEXT:    // =>This Inner Loop Header: Depth=1
; ASM-NEXT:    // Label of block must be emitted
; ASM-NEXT:  .LLhwloop_start0:
; ASM-NEXT:    { addi32 r4, r4, 4; ld32 r3, r4, 0 }
; ASM-NEXT:    { nop; s_lw_post_imm r5, r2, 1 }
; ASM-NEXT:    { nop; nop }
; ASM-NEXT:    { nop; mull r3, r3, r5 }
; ASM-NEXT:  .LLhwloop_end0:
; ASM-NEXT:    { nop; add32 r1, r1, r3 }
; ASM-NEXT:  .LBB2_3: // %exit
; ASM-NEXT:    { nop; addi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa sp, 0
; ASM-NEXT:    { nop; jalr r0, lr, 0 }
; PREGREEDY-LABEL: name: qor_dual_load_mac_stream
; PREGREEDY: bb.0.entry:
; PREGREEDY-NEXT:   successors: %bb.1(0x50000000), %bb.4(0x30000000)
; PREGREEDY-NEXT:   liveins: $r1, $r2, $r3
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $r1
; PREGREEDY-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $r2
; PREGREEDY-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $r3
; PREGREEDY-NEXT:   [[LOADI32_:%[0-9]+]]:gpr32 = LOADI32 0
; PREGREEDY-NEXT:   [[SLT32_:%[0-9]+]]:gpr32 = SLT32 [[LOADI32_]], [[COPY2]]
; PREGREEDY-NEXT:   [[XORI32_:%[0-9]+]]:gpr32 = XORI32 [[SLT32_]], 1
; PREGREEDY-NEXT:   BEQZ_W [[XORI32_]], %bb.1
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT: bb.4:
; PREGREEDY-NEXT:   successors: %bb.3(0x80000000)
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   B %bb.3
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT: bb.1.loop.preheader:
; PREGREEDY-NEXT:   successors: %bb.2(0x80000000)
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   LoopStart [[COPY2]], 0
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT: bb.2.loop:
; PREGREEDY-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   [[LD32_:%[0-9]+]]:gpr32 = LD32 [[COPY]], 0 :: (load (s32) from %ir.lsr.iv1)
; PREGREEDY-NEXT:   [[S_LW_POST_IMM:%[0-9]+]]:gpr32, [[COPY1:%[0-9]+]]:gpr32 = S_LW_POST_IMM [[COPY1]], 1 :: (load (s32) from %ir.lsr.iv)
; PREGREEDY-NEXT:   [[MULL:%[0-9]+]]:gpr32 = MULL [[LD32_]], [[S_LW_POST_IMM]]
; PREGREEDY-NEXT:   [[COPY:%[0-9]+]]:gpr32 = ADDI32 [[COPY]], 4
; PREGREEDY-NEXT:   [[LOADI32_:%[0-9]+]]:gpr32 = ADD32 [[LOADI32_]], [[MULL]]
; PREGREEDY-NEXT:   PseudoLoopEnd %bb.2
; PREGREEDY-NEXT:   B %bb.3
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT: bb.3.exit:
; PREGREEDY-NEXT:   $r1 = COPY [[LOADI32_]]
; PREGREEDY-NEXT:   RET implicit $r15, implicit $r1, implicit $r15
;
; PREPOST-LABEL: name: qor_dual_load_mac_stream
; PREPOST: bb.0.entry:
; PREPOST-NEXT:   successors: %bb.1(0x50000000), %bb.3(0x30000000)
; PREPOST-NEXT:   liveins: $r1, $r2, $r3, $r0
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; PREPOST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; PREPOST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; PREPOST-NEXT:   $r4 = MOVE32 $r1
; PREPOST-NEXT:   $r1 = ADDI32_W $r0, 0
; PREPOST-NEXT:   $r5 = SLT32 $r1, $r3
; PREPOST-NEXT:   $r5 = XORI32 killed $r5, 1
; PREPOST-NEXT:   BNEZ_W $r5, %bb.3
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT: bb.1.loop.preheader:
; PREPOST-NEXT:   successors: %bb.2(0x80000000)
; PREPOST-NEXT:   liveins: $r1, $r2, $r3, $r4
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   SET_HWLOOP_F2_W 0, %bb.2, %bb.2, $r3, implicit-def $sfr
; PREPOST-NEXT:   NOP
; PREPOST-NEXT:   NOP
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT: bb.2.loop:
; PREPOST-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
; PREPOST-NEXT:   liveins: $r1, $r2, $r4
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r3 = LD32 $r4, 0 :: (load (s32) from %ir.lsr.iv1)
; PREPOST-NEXT:   $r5, $r2 = S_LW_POST_IMM killed $r2, 1 :: (load (s32) from %ir.lsr.iv)
; PREPOST-NEXT:   $r3 = MULL killed $r3, killed $r5
; PREPOST-NEXT:   $r4 = ADDI32 killed $r4, 4
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r3
; PREPOST-NEXT:   PseudoLoopEnd %bb.2
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT: bb.3.exit:
; PREPOST-NEXT:   liveins: $r1
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; PREPOST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; PREPOST-NEXT:   $r0 = JALR_W $r15, 0, implicit $r1
;
; POST-LABEL: name: qor_dual_load_mac_stream
; POST: bb.0.entry:
; POST-NEXT:   successors: %bb.1(0x50000000), %bb.3(0x30000000)
; POST-NEXT:   liveins: $r1, $r2, $r3, $r0
; POST-NEXT: {{  $}}
; POST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; POST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; POST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; POST-NEXT:   $r4 = MOVE32_E3_E2_ALU2_R killed $r1
; POST-NEXT:   $r1 = ADDI32_E2_E0_ALU0_RI20 $r0, 0
; POST-NEXT:   $r5 = SLT32_E3_E2_ALU2_RR $r1, $r3
; POST-NEXT:   $r5 = XORI32_E2_E1_ALU1_RI20 killed $r5, 1
; POST-NEXT:   BNEZ_W killed $r5, %bb.3
; POST-NEXT: {{  $}}
; POST-NEXT: bb.1.loop.preheader:
; POST-NEXT:   successors: %bb.2(0x80000000)
; POST-NEXT:   liveins: $r1, $r2, $r3, $r4
; POST-NEXT: {{  $}}
; POST-NEXT:   SET_HWLOOP_F2_E2_E0_ALU0_HWLRIIR 0, %bb.2, %bb.2, killed $r3, implicit-def $sfr
; POST-NEXT:   NOP
; POST-NEXT:   NOP
; POST-NEXT: {{  $}}
; POST-NEXT: bb.2.loop:
; POST-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
; POST-NEXT:   liveins: $r1, $r2, $r4
; POST-NEXT: {{  $}}
; POST-NEXT:   BUNDLE 0, 0, implicit-def $r3, implicit-def $r4, implicit killed $r4 :: (load (s32) from %ir.lsr.iv1) {
; POST-NEXT:     $r3 = S_LW_WITH_IMM_E2_E1_LOAD1_RI6 $r4, 0 :: (load (s32) from %ir.lsr.iv1)
; POST-NEXT:     $r4 = ADDI32_E2_E0_ALU0_RI20 killed $r4, 4
; POST-NEXT:   }
; POST-NEXT:   $r5, $r2 = S_LW_POST_IMM_E3_E2_LOAD1_RI6 killed $r2, 1 :: (load (s32) from %ir.lsr.iv)
; POST-NEXT:   NOP
; POST-NEXT:   $r3 = MULL_E3_E2_MAC1_RR killed $r3, killed $r5
; POST-NEXT:   $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r3
; POST-NEXT:   PseudoLoopEnd %bb.2
; POST-NEXT: {{  $}}
; POST-NEXT: bb.3.exit:
; POST-NEXT:   liveins: $r1
; POST-NEXT: {{  $}}
; POST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; POST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; POST-NEXT:   $r0 = JALR_W $r15, 0, implicit killed $r1
                                     ptr nocapture readonly %h, i32 %n) {
; Option A containment: no pre-RA SMS multi-member BUNDLE freeze.
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit
loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %xi = getelementptr i32, ptr %x, i32 %i
  %hi = getelementptr i32, ptr %h, i32 %i
  %xv = load i32, ptr %xi, align 4
  %hv = load i32, ptr %hi, align 4
  %prod = mul i32 %xv, %hv
  %acc.next = add i32 %acc, %prod
  %i.next = add i32 %i, 1
  %c = icmp slt i32 %i.next, %n
  br i1 %c, label %loop, label %exit
exit:
  %r = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  ret i32 %r
}

; Critical-path + independent side work — pressure/critical stay primary
; under matching-frontier tryCandidate; pre-RA never member-stamps.
define i32 @qor_critical_and_side(i32 %a, i32 %b, i32 %c) {
; ASM-LABEL: qor_critical_and_side:
; ASM:       // %bb.0: // %entry
; ASM-NEXT:    { nop; xor32 r0, r0, r0 }
; ASM-NEXT:    { nop; subi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa_offset 8
; ASM-NEXT:    { nop; or32 r2, r2, r3; xor32 r4, r2, r3 }
; ASM-NEXT:    { nop; add32 r2, r4, r2 }
; ASM-NEXT:    { nop; add32 r1, r1, r2 }
; ASM-NEXT:    { nop; addi32 r1, r1, 6 }
; ASM-NEXT:    { nop; addi32 sp, sp, 8 }
; ASM-NEXT:    .cfi_def_cfa sp, 0
; ASM-NEXT:    { nop; jalr r0, lr, 0 }
; PREGREEDY-LABEL: name: qor_critical_and_side
; PREGREEDY: bb.0.entry:
; PREGREEDY-NEXT:   liveins: $r1, $r2, $r3
; PREGREEDY-NEXT: {{  $}}
; PREGREEDY-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $r2
; PREGREEDY-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $r3
; PREGREEDY-NEXT:   [[XOR32_:%[0-9]+]]:gpr32 = XOR32 [[COPY]], [[COPY1]]
; PREGREEDY-NEXT:   [[OR32_:%[0-9]+]]:gpr32 = OR32 [[COPY]], [[COPY1]]
; PREGREEDY-NEXT:   [[ADD32_:%[0-9]+]]:gpr32 = ADD32 [[XOR32_]], [[OR32_]]
; PREGREEDY-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $r1
; PREGREEDY-NEXT:   [[ADD32_1:%[0-9]+]]:gpr32 = ADD32 [[COPY2]], [[ADD32_]]
; PREGREEDY-NEXT:   [[ADDI32_:%[0-9]+]]:gpr32 = ADDI32 [[ADD32_1]], 6
; PREGREEDY-NEXT:   $r1 = COPY [[ADDI32_]]
; PREGREEDY-NEXT:   RET implicit $r15, implicit $r1, implicit $r15
;
; PREPOST-LABEL: name: qor_critical_and_side
; PREPOST: bb.0.entry:
; PREPOST-NEXT:   liveins: $r1, $r2, $r3, $r0
; PREPOST-NEXT: {{  $}}
; PREPOST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; PREPOST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; PREPOST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; PREPOST-NEXT:   $r4 = XOR32 $r2, $r3
; PREPOST-NEXT:   $r2 = OR32 killed $r2, killed $r3
; PREPOST-NEXT:   $r2 = ADD32 killed $r4, killed $r2
; PREPOST-NEXT:   $r1 = ADD32 killed $r1, killed $r2
; PREPOST-NEXT:   $r1 = ADDI32 killed $r1, 6
; PREPOST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; PREPOST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; PREPOST-NEXT:   $r0 = JALR_W $r15, 0, implicit $r1
;
; POST-LABEL: name: qor_critical_and_side
; POST: bb.0.entry:
; POST-NEXT:   liveins: $r1, $r2, $r3, $r0
; POST-NEXT: {{  $}}
; POST-NEXT:   $r0 = frame-setup XOR32 $r0, $r0
; POST-NEXT:   $r13 = frame-setup SUBI32 $r13, 8
; POST-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 8
; POST-NEXT:   BUNDLE 1, 0, implicit-def $r4, implicit-def $r2, implicit killed $r2, implicit killed $r3 {
; POST-NEXT:     $r4 = XOR32_E3_E2_ALU2_RR $r2, $r3
; POST-NEXT:     $r2 = OR32_E3_E1_ALU1_RR killed $r2, killed $r3
; POST-NEXT:   }
; POST-NEXT:   $r2 = ADD32_E3_E2_ALU2_RR killed $r4, killed $r2
; POST-NEXT:   $r1 = ADD32_E3_E2_ALU2_RR killed $r1, killed $r2
; POST-NEXT:   $r1 = ADDI32_E2_E1_ALU1_RI20 killed $r1, 6
; POST-NEXT:   $r13 = frame-destroy ADDI32_W $r13, 8
; POST-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa $r13, 0
; POST-NEXT:   $r0 = JALR_W $r15, 0, implicit killed $r1
entry:
  ; Longer chain on %a (critical).
  %a1 = add i32 %a, 1
  %a2 = add i32 %a1, 2
  %a3 = add i32 %a2, 3
  ; Independent side work on %b/%c (ILP / packing).
  %s = xor i32 %b, %c
  %t = or i32 %b, %c
  %u = add i32 %s, %t
  %r = add i32 %a3, %u
  ret i32 %r
}

; Soft-exit stats: multi-MI exact finalize fires on qual kernels; the
; 'failed exact no-split' counter may be zero under multi-stage SMS containment (the post-RA
; field-order-RAW fix, companion regression postra-field-order-raw-narrow-store.mir,
; correctly fails commit for cycles whose field-order permutation would create a
; no-forwarding RAW hazard on adjacent narrow stores; such cycles fall back to
; sequential parcels — correct product behavior, not a regression); unstamped
; hard-root counter stays at zero (silent in -stats).
; STATS: multi-MI cycles finalized as BUNDLE
; STATS-NOT: unstamped multi-member hard BUNDLE roots at post-RA
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; STATS: {{.*}}
