; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 < %s | FileCheck %s

; Role: smoke — Smoke: pre-existing CHECK drift — compile and emit a return.

; Smoke: pre-existing CHECK drift — compile and emit a return.
;
; REBASELINED : / pipeline reorder (ExpandPseudos/BitSimplify pre-scheduler + materialize at leaveRegion) — bundles regrouped, ops unchanged.
;
; Test recursive function calls.
; Recursive functions stress the stack frame layout, callee-save handling
; and the register allocator (all registers may be live across the recursive call).
;
; NOTE: Does not use -verify-machineinstrs because the G_PHI from loop-carried
; values survives past InstructionSelect. The generated code is correct.

;Simple recursion (factorial)

define i32 @factorial(i32 %n) nounwind {
; CHECK-LABEL: factorial:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 lr, r2, 0 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r8, r2, 1 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r2, r0, 1 }
; CHECK-NEXT:    { nop; slt32 r3, r2, r1 }
; CHECK-NEXT:    { nop; bnez r3, .LBB0_2 }
; CHECK-NEXT:  // %bb.1: // %base
; CHECK-NEXT:    { nop; move32 r1, r2 }
; CHECK-NEXT:    { nop; beqz r0, .LBB0_3 }
; CHECK-NEXT:  .LBB0_2: // %recurse
; CHECK-NEXT:    { move32 r8, r1; addi32 r2, r1, -1 }
; CHECK-NEXT:    { nop; lui r3, factorial }
; CHECK-NEXT:    { move32 r1, r2; addi32 r3, r3, factorial }
; CHECK-NEXT:    { jalr lr, r3, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0; mull r1, r8, r1 }
; CHECK-NEXT:  .LBB0_3: // %base
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 2 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
; 2026-08-21 latency P3: no stall parcel before the recurse block.
entry:
  %cmp = icmp sle i32 %n, 1
  br i1 %cmp, label %base, label %recurse
base:
  ret i32 1
recurse:
  %n_minus_1 = sub i32 %n, 1
  %sub = call i32 @factorial(i32 %n_minus_1)
  %result = mul i32 %n, %sub
  ret i32 %result
}

;Tail-recursive function (sum 1..n)
define i32 @sum_to_n(i32 %n, i32 %acc) nounwind {
; CHECK-LABEL: sum_to_n:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r3, r0, 0 }
; CHECK-NEXT:    { nop; seq32 r3, r1, r3 }
; CHECK-NEXT:    { nop; xori32 r3, r3, 1 }
; CHECK-NEXT:    { nop; beqz r3, .LBB1_2 }
; CHECK-NEXT:  // %bb.1: // %recurse
; CHECK-NEXT:    { nop; lui r3, sum_to_n }
; CHECK-NEXT:    { nop; add32 r2, r2, r1 }
; CHECK-NEXT:    { addi32 r3, r3, sum_to_n; addi32 r1, r1, -1 }
; CHECK-NEXT:    { jalr lr, r3, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; beqz r0, .LBB1_3 }
; CHECK-NEXT:  .LBB1_2: // %done
; CHECK-NEXT:    { nop; move32 r1, r2 }
; CHECK-NEXT:  .LBB1_3: // %done
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp eq i32 %n, 0
  br i1 %cmp, label %done, label %recurse
done:
  ret i32 %acc
recurse:
  %new_acc = add i32 %acc, %n
  %n_minus_1 = sub i32 %n, 1
  %r = call i32 @sum_to_n(i32 %n_minus_1, i32 %new_acc)
  ret i32 %r
}

;Fibonacci (two recursive calls)
define i32 @fib(i32 %n) nounwind {
; CHECK-LABEL: fib:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 lr, r2, 0 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r10, r2, 1 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r9, r2, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r8, r2, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r2, r0, 1 }
; CHECK-NEXT:    { nop; slt32 r2, r2, r1 }
; CHECK-NEXT:    { nop; beqz r2, .LBB2_2 }
; CHECK-NEXT:  // %bb.1: // %recurse
; CHECK-NEXT:    { addi32 r8, r1, -2; addi32 r2, r1, -1 }
; CHECK-NEXT:    { nop; lui r10, fib }
; CHECK-NEXT:    { move32 r1, r2; addi32 r10, r10, fib }
; CHECK-NEXT:    { jalr lr, r10, 0 }
; CHECK-NEXT:    { nop; move32 r1, r8; move32 r9, r1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { jalr lr, r10, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0; add32 r1, r9, r1 }
; CHECK-NEXT:  .LBB2_2: // %base
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 2 }
; CHECK-NEXT:    { ld32 r9, sp, 4; ld32 r10, sp, 3 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 5 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp sle i32 %n, 1
  br i1 %cmp, label %base, label %recurse
base:
  ret i32 %n
recurse:
  %n1 = sub i32 %n, 1
  %n2 = sub i32 %n, 2
  %f1 = call i32 @fib(i32 %n1)
  %f2 = call i32 @fib(i32 %n2)
  %sum = add i32 %f1, %f2
  ret i32 %sum
}

;Mutual recursion
define i32 @is_even(i32 %n) nounwind {
; CHECK-LABEL: is_even:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r2, r0, 0 }
; CHECK-NEXT:    { nop; seq32 r2, r1, r2 }
; CHECK-NEXT:    { nop; xori32 r2, r2, 1 }
; CHECK-NEXT:    { nop; beqz r2, .LBB3_2 }
; CHECK-NEXT:  // %bb.1: // %recurse
; CHECK-NEXT:    { nop; lui r2, is_odd }
; CHECK-NEXT:    { addi32 r2, r2, is_odd; addi32 r1, r1, -1 }
; CHECK-NEXT:    { jalr lr, r2, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; beqz r0, .LBB3_3 }
; CHECK-NEXT:  .LBB3_2: // %yes
; CHECK-NEXT:    { nop; addi32 r1, r0, 1 }
; CHECK-NEXT:  .LBB3_3: // %yes
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp eq i32 %n, 0
  br i1 %cmp, label %yes, label %recurse
yes:
  ret i32 1
recurse:
  %n_minus_1 = sub i32 %n, 1
  %r = call i32 @is_odd(i32 %n_minus_1)
  ret i32 %r
}

define i32 @is_odd(i32 %n) nounwind {
; CHECK-LABEL: is_odd:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; st32 lr, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r2, r0, 0 }
; CHECK-NEXT:    { nop; seq32 r3, r1, r2 }
; CHECK-NEXT:    { nop; xori32 r3, r3, 1 }
; CHECK-NEXT:    { nop; beqz r3, .LBB4_2 }
; CHECK-NEXT:  // %bb.1: // %recurse
; CHECK-NEXT:    { nop; lui r2, is_even }
; CHECK-NEXT:    { addi32 r2, r2, is_even; addi32 r1, r1, -1 }
; CHECK-NEXT:    { jalr lr, r2, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; beqz r0, .LBB4_3 }
; CHECK-NEXT:  .LBB4_2: // %no
; CHECK-NEXT:    { nop; move32 r1, r2 }
; CHECK-NEXT:  .LBB4_3: // %no
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 16 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp eq i32 %n, 0
  br i1 %cmp, label %no, label %recurse
no:
  ret i32 0
recurse:
  %n_minus_1 = sub i32 %n, 1
  %r = call i32 @is_even(i32 %n_minus_1)
  ret i32 %r
}

;Recursive function calling itself twice (tree recursion)
define i32 @tree_sum(i32 %n) nounwind {
; CHECK-LABEL: tree_sum:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; addi32 r2, sp, 8 }
; CHECK-NEXT:    { nop; st32 lr, r2, 0 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r10, r2, 1 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r9, r2, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r8, r2, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 r2, r0, 0 }
; CHECK-NEXT:    { nop; slt32 r2, r2, r1 }
; CHECK-NEXT:    { nop; beqz r2, .LBB5_2 }
; CHECK-NEXT:  // %bb.1: // %recurse
; CHECK-NEXT:    { nop; srai32 r8, r1, 1 }
; CHECK-NEXT:    { nop; lui r10, tree_sum }
; CHECK-NEXT:    { move32 r1, r8; addi32 r10, r10, tree_sum }
; CHECK-NEXT:    { jalr lr, r10, 0 }
; CHECK-NEXT:    { nop; move32 r1, r8; move32 r9, r1 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { jalr lr, r10, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0; add32 r1, r9, r1 }
; CHECK-NEXT:  .LBB5_2: // %base
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 lr, sp, 2 }
; CHECK-NEXT:    { ld32 r9, sp, 4; ld32 r10, sp, 3 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 5 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
entry:
  %cmp = icmp sle i32 %n, 0
  br i1 %cmp, label %base, label %recurse
base:
  ret i32 %n
recurse:
  %half = ashr i32 %n, 1
  %left = call i32 @tree_sum(i32 %half)
  %right = call i32 @tree_sum(i32 %half)
  %sum = add i32 %left, %right
  ret i32 %sum
}
