; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -verify-machineinstrs -global-isel-abort=1 -O2 < %s | FileCheck %s


;
; REGRESSION TEST: Caller-saved register clobber across calls.
;
; Purpose: Verify that caller-saved registers (R1-R7 for GPR, D0-D7 for DR64)
; are correctly spilled and reloaded around function calls. When a caller-saved
; register holds a live value that must survive across a call, the register
; allocator must either move it to a callee-saved register or spill it to the
; stack.
;
; Why this test exists:
; Caller-saved registers are clobbered by function calls. The register
; allocator must correctly track which values are live across calls and
; ensure they are not assigned to caller-saved registers if they need to
; survive. CSR GPRs are R8-R11 + R14 (always CSR; R14 is FP when hasFP).
; R12 is call-clobbered. With 8 CSR DR64s (D8-D15), the allocator spills
; to stack when callee-saved registers are exhausted.
;
; What these tests guard:
; 1. Live values across calls are not lost when caller-saved registers are clobbered
; 2. The allocator prefers callee-saved registers for values live across calls
; 3. Stack spills happen when callee-saved registers are insufficient
; 4. Values are correctly reloaded after the call returns
; 5. Both GPR and DR64 caller-saved registers are handled
;
; If these tests fail, investigate the register allocator's spill logic and
; the call-preserved mask for the Haydn calling convention.
; Do NOT update CHECK lines without understanding the clobber pattern.
;


declare i32 @clobber_gpr()
declare i64 @clobber_dr64()
declare void @clobber_all()

;Test 1: GPR caller-saved registers live across call.
;R1-R7 are caller-saved. Values in R1-R7 at the call site must be saved.

define i32 @test_gpr_caller_saved_across_call(i32 %a, i32 %b, i32 %c) nounwind {
; CHECK-LABEL: test_gpr_caller_saved_across_call:
; CHECK:       // #<spill-kpi> @test_gpr_caller_saved_across_call spills=4 spill-bytes=16 reloads=4 reload-bytes=16
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32 r4, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r4, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r4, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r4, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r4, 3 }
; CHECK-NEXT:    { move32 r8, r1; move32 r9, r2; nop }
; CHECK-NEXT:    { move32 r10, r3; nop; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { add32 r2, r8, r9; xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { add32 r2, r2, r10; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
; %a, %b, %c arrive in R1, R2, R3 (caller-saved). All three must survive
; the call to @clobber_gpr. The allocator should move them to callee-saved
; registers or spill to stack.
  %call_result = call i32 @clobber_gpr()
  %s1 = add i32 %a, %b
  %s2 = add i32 %s1, %c
  %s3 = add i32 %s2, %call_result
  ret i32 %s3
}

;Test 2: DR64 caller-saved registers live across call.
;D0-D7 are caller-saved. Values in D0-D7 at the call site must be saved.

define i64 @test_dr64_caller_saved_across_call(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: test_dr64_caller_saved_across_call:
; CHECK:       // #<spill-kpi> @test_dr64_caller_saved_across_call spills=3 spill-bytes=20 reloads=3 reload-bytes=20
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 32; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, sp, 7 }
; CHECK-NEXT:    { addi32 r1, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d9, r1, 0 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d8, r1, 1 }
; CHECK-NEXT:    { or64 d8, d0, d0; or64 d9, d1, d1; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_dr64; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add64 d1, d8, d9; nop }
; CHECK-NEXT:    { add64 d0, d1, d0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d9, sp, 1; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d8, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 7; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 32; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
; %a, %b arrive in D0, D1 (caller-saved). Both must survive the call.
  %call_result = call i64 @clobber_dr64()
  %s1 = add i64 %a, %b
  %s2 = add i64 %s1, %call_result
  ret i64 %s2
}

;Test 3: All GPR caller-saved registers (R1-R7) holding live values.
;7 live i32 values across a call forces heavy spill or callee-saved usage.

define i32 @test_all_gpr_caller_saved(i32 %a, i32 %b, i32 %c, i32 %d,
; CHECK-LABEL: test_all_gpr_caller_saved:
; CHECK:       // #<spill-kpi> @test_all_gpr_caller_saved spills=8 spill-bytes=32 reloads=8 reload-bytes=32
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    { addi32 r12, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r12, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm fp, r12, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r11, r12, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r12, 3 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r12, 4 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r12, 5 }
; CHECK-NEXT:    { move32 r9, r2; move32 r10, r3; s_sw_with_imm r1, sp, 3 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { move32 r11, r4; move32 fp, r5; s_sw_with_imm r7, sp, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { move32 r8, r6; nop; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { s_lw_with_imm r2, sp, 3; nop; s_lw_with_imm r3, sp, 2 } // 8-byte Folded Reload
; CHECK-NEXT:    // 4-byte Reload4-byte Reload
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r9; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r10; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r11; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, fp; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r8; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r3; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm fp, sp, 5; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r11, sp, 6; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 7; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 8; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 9; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 40; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
                                       i32 %e, i32 %f, i32 %g) nounwind {
entry:
; All 7 args arrive in R1-R7. The call clobbers all of them.
; At least 7 values must survive (some in callee-saved, some spilled).
; After call, values must be reloaded from stack or callee-saved registers
  %call_result = call i32 @clobber_gpr()
  %s1 = add i32 %a, %b
  %s2 = add i32 %s1, %c
  %s3 = add i32 %s2, %d
  %s4 = add i32 %s3, %e
  %s5 = add i32 %s4, %f
  %s6 = add i32 %s5, %g
  %s7 = add i32 %s6, %call_result
  ret i32 %s7
}

;Test 4: Multiple calls clobbering caller-saved registers repeatedly.
;Values must survive across multiple call boundaries.

define i32 @test_repeated_clobber(i32 %x) nounwind {
; CHECK-LABEL: test_repeated_clobber:
; CHECK:       // #<spill-kpi> @test_repeated_clobber spills=6 spill-bytes=24 reloads=6 reload-bytes=24
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 32; nop }
; CHECK-NEXT:    { addi32 r2, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r2, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm fp, r2, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r11, r2, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r2, 3 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r2, 4 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r2, 5 }
; CHECK-NEXT:    { move32 r8, r1; nop; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 r9, r1; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 r10, r1; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 r11, r1; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; move32 fp, r1; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_gpr; nop }
; CHECK-NEXT:    { add32 r2, r8, r9; xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { add32 r2, r2, r10; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, r11; nop; nop }
; CHECK-NEXT:    { add32 r2, r2, fp; nop; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm fp, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r11, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 5; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 6; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 7; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 32; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
; %x must survive across all 5 calls
  %r1 = call i32 @clobber_gpr()
  %r2 = call i32 @clobber_gpr()
  %r3 = call i32 @clobber_gpr()
  %r4 = call i32 @clobber_gpr()
  %r5 = call i32 @clobber_gpr()
  %s1 = add i32 %x, %r1
  %s2 = add i32 %s1, %r2
  %s3 = add i32 %s2, %r3
  %s4 = add i32 %s3, %r4
  %s5 = add i32 %s4, %r5
  ret i32 %s5
}

;Test 5: Both GPR and DR64 caller-saved registers clobbered by one call.
;void @clobber_all clobbers all caller-saved registers in both banks.

define i64 @test_both_banks_clobbered(i32 %a, i64 %b) nounwind {
; CHECK-LABEL: test_both_banks_clobbered:
; CHECK:       // #<spill-kpi> @test_both_banks_clobbered spills=3 spill-bytes=16 reloads=3 reload-bytes=16
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32 r2, sp, 16; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r2, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r2, 1 }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d8, sp, 1 }
; CHECK-NEXT:    { move32 r8, r1; or64 d8, d0, d0; nop }
; CHECK-NEXT:    { nop; jal lr, clobber_all; nop }
; CHECK-NEXT:    { sext32t64 d0, r8; xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { slli64 d0, d0, 32; nop; nop }
; CHECK-NEXT:    { srli64 d0, d0, 32; nop; nop }
; CHECK-NEXT:    { add64 d0, d8, d0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { d_ldw_with_imm d8, sp, 1; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
entry:
; %a (GPR R1) and %b (DR64 D0) are both caller-saved and must survive.
  call void @clobber_all()
  %ext_a = zext i32 %a to i64
  %result = add i64 %b, %ext_a
  ret i64 %result
}
