; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s
; independent chains packable. Pin folded immediate + add32 presence.

define i32 @critical_path_priority(i32 %a, i32 %b) {
; The constant adds collapse into a single addi32; one register-register add
; remains for the %x dependency.
; CHECK-LABEL: critical_path_priority:
; CHECK:       // #<spill-kpi> @critical_path_priority spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 36; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %a1 = add i32 %a, 1
  %a2 = add i32 %a1, 2
  %a3 = add i32 %a2, 3

  %b1 = add i32 %b, 10
  %b2 = add i32 %b1, 20

  %result = add i32 %a3, %b2
  ret i32 %result
}

; Test that a long chain with memory operations gets scheduled so that
; loads are issued early. The load for the critical path should be
; prioritized over independent computation.
define i32 @critical_path_with_memory(ptr %p, i32 %x) {
; The load should appear in the function body.
; +1+2 folds into one addi32; the %x add stays register-register.
; CHECK-LABEL: critical_path_with_memory:
; CHECK:       // #<spill-kpi> @critical_path_with_memory spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { s_lw_with_imm r1, r1, 0; nop; nop }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { add32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { addi32 r1, r1, 3; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v = load i32, ptr %p
  %r1 = add i32 %v, 1
  %r2 = add i32 %r1, 2
  %r3 = add i32 %r2, %x
  ret i32 %r3
}
