; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s


;
; Test shift and rotate operations for Haydn.
; Complements the basic shift.ll test with edge cases, constant shifts
; shift+mask patterns, and sign-extension-via-shift idioms.

;Shift by constant amounts

; Shift by 1 (smallest non-zero)


define i32 @shl_by_1(i32 %x) {
; CHECK-LABEL: shl_by_1:
; CHECK:       // #<spill-kpi> @shl_by_1 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = shl i32 %x, 1
  ret i32 %r
}

define i32 @lshr_by_1(i32 %x) {
; CHECK-LABEL: lshr_by_1:
; CHECK:       // #<spill-kpi> @lshr_by_1 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srli32 r1, r1, 1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = lshr i32 %x, 1
  ret i32 %r
}

define i32 @ashr_by_1(i32 %x) {
; CHECK-LABEL: ashr_by_1:
; CHECK:       // #<spill-kpi> @ashr_by_1 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srai32 r1, r1, 1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = ashr i32 %x, 1
  ret i32 %r
}

; Shift by 0 (identity — optimizer eliminates the shift entirely)
define i32 @shl_by_0(i32 %x) {
; CHECK-LABEL: shl_by_0:
; CHECK:       // #<spill-kpi> @shl_by_0 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = shl i32 %x, 0
  ret i32 %r
}

; Shift by 31 (largest meaningful shift for i32)
define i32 @shl_by_31(i32 %x) {
; CHECK-LABEL: shl_by_31:
; CHECK:       // #<spill-kpi> @shl_by_31 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 31; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = shl i32 %x, 31
  ret i32 %r
}

define i32 @lshr_by_31(i32 %x) {
; CHECK-LABEL: lshr_by_31:
; CHECK:       // #<spill-kpi> @lshr_by_31 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srli32 r1, r1, 31; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = lshr i32 %x, 31
  ret i32 %r
}

define i32 @ashr_by_31(i32 %x) {
; CHECK-LABEL: ashr_by_31:
; CHECK:       // #<spill-kpi> @ashr_by_31 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srai32 r1, r1, 31; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = ashr i32 %x, 31
  ret i32 %r
}

; Shift by 5 (mid-range constant)
define i32 @shl_by_5(i32 %x) {
; CHECK-LABEL: shl_by_5:
; CHECK:       // #<spill-kpi> @shl_by_5 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 5; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = shl i32 %x, 5
  ret i32 %r
}

;Variable shifts

define i32 @shl_variable(i32 %x, i32 %s) {
; CHECK-LABEL: shl_variable:
; CHECK:       // #<spill-kpi> @shl_variable spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { sll32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = shl i32 %x, %s
  ret i32 %r
}

define i32 @lshr_variable(i32 %x, i32 %s) {
; CHECK-LABEL: lshr_variable:
; CHECK:       // #<spill-kpi> @lshr_variable spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srl32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = lshr i32 %x, %s
  ret i32 %r
}

define i32 @ashr_variable(i32 %x, i32 %s) {
; CHECK-LABEL: ashr_variable:
; CHECK:       // #<spill-kpi> @ashr_variable spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { sra32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %r = ashr i32 %x, %s
  ret i32 %r
}

;Sign-extension via shift (common C pattern: (x << 16) >> 16)

define i32 @sext_via_shift_16(i32 %x) {
; CHECK-LABEL: sext_via_shift_16:
; CHECK:       // #<spill-kpi> @sext_via_shift_16 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 16; nop; nop }
; CHECK-NEXT:    { srai32 r1, r1, 16; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %shl = shl i32 %x, 16
  %shr = ashr i32 %shl, 16
  ret i32 %shr
}

define i32 @sext_via_shift_24(i32 %x) {
; CHECK-LABEL: sext_via_shift_24:
; CHECK:       // #<spill-kpi> @sext_via_shift_24 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 24; nop; nop }
; CHECK-NEXT:    { srai32 r1, r1, 24; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %shl = shl i32 %x, 24
  %shr = ashr i32 %shl, 24
  ret i32 %shr
}

;Shift with multiple uses (should not be duplicated)

define i32 @shift_multi_use(i32 %x, i32 %y) {
; CHECK-LABEL: shift_multi_use:
; CHECK:       // #<spill-kpi> @shift_multi_use spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { slli32 r1, r1, 2; nop; nop }
; CHECK-NEXT:    { add32 r2, r1, r2; nop; nop }
; CHECK-NEXT:    { mull r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %a = shl i32 %x, 2
  %b = add i32 %a, %y
  %c = mul i32 %b, %a
  ret i32 %c
}

;Shift+mask patterns (byte/halfword extraction)

; Extract byte 1: (x >> 8) & 0xFF
define i32 @extract_byte1(i32 %x) {
; CHECK-LABEL: extract_byte1:
; CHECK:       // #<spill-kpi> @extract_byte1 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { srli32 r1, r1, 8; nop; nop }
; CHECK-NEXT:    { andi32 r1, r1, 255; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %shr = lshr i32 %x, 8
  %and = and i32 %shr, 255
  ret i32 %and
}

; Merge two 16-bit fields into 32 bits: (lo & 0xFFFF) | (hi << 16)
define i32 @merge_halves(i32 %lo, i32 %hi) {
; CHECK-LABEL: merge_halves:
; CHECK:       // #<spill-kpi> @merge_halves spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { andi32 r1, r1, 65535; slli32 r2, r2, 16 }
; CHECK-NEXT:    { or32 r1, r1, r2; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %lo_masked = and i32 %lo, 65535
  %hi_shifted = shl i32 %hi, 16
  %result = or i32 %lo_masked, %hi_shifted
  ret i32 %result
}
