; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Soft-float G_FNEG / G_FABS: generic LegalizerHelper::lower (not libcall, not Haydn custom).


;
; Soft-float G_FNEG / G_FABS: generic LegalizerHelper::lower (not libcall,
; not Haydn custom). Sign-bit XOR / magnitude AND on IEEE bits in GPR/DR64.
; fneg → XOR with 0x8000…0; fabs → AND with 0x7FFF…F.
; neg_then_add: fneg+fadd may strength-reduce to __subsf3.

; float fneg — XOR32 with 0x80000000

define float @negf(float noundef %a) {
; CHECK-LABEL: negf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { lui r2, 2048; nop }
; CHECK-NEXT:    { addi32_w r2, r2, 0; nop }
; CHECK-NEXT:    { xor32 r1, r1, r2; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = fneg float %a
  ret float %r
}

; float fabs — AND32 with 0x7FFFFFFF
define float @fabsf_test(float noundef %a) {
; CHECK-LABEL: fabsf_test:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { lui r2, 2048; nop }
; CHECK-NEXT:    { addi32_w r2, r2, -1; nop }
; CHECK-NEXT:    { and32 r1, r1, r2; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call float @llvm.fabs.f32(float %a)
  ret float %r
}

declare float @llvm.fabs.f32(float)

; double fneg — XOR64 with sign mask on DR64
define double @negd(double noundef %a) {
; CHECK-LABEL: negd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 0; nop }
; CHECK-NEXT:    { st32 r1, sp, 2; nop } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { lui r1, 2048; nop }
; CHECK-NEXT:    { addi32_w r1, r1, 0; nop }
; CHECK-NEXT:    { st32 r1, sp, 3; nop } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { ld64 d1, sp, 1; nop } // 8-byte Folded Reload
; CHECK-NEXT:    // 8-byte Reload
; CHECK-NEXT:    { xor64 d0, d0, d1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 24; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = fneg double %a
  ret double %r
}

; double fabs — AND64 with magnitude mask on DR64
define double @fabsd_test(double noundef %a) {
; CHECK-LABEL: fabsd_test:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, r0, -1; nop }
; CHECK-NEXT:    { st32 r1, sp, 2; nop } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { lui r1, 2048; nop }
; CHECK-NEXT:    { addi32_w r1, r1, -1; nop }
; CHECK-NEXT:    { st32 r1, sp, 3; nop } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { ld64 d1, sp, 1; nop } // 8-byte Folded Reload
; CHECK-NEXT:    // 8-byte Reload
; CHECK-NEXT:    { and64 d0, d0, d1; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 24; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call double @llvm.fabs.f64(double %a)
  ret double %r
}

declare double @llvm.fabs.f64(double)

; fneg + fadd may fold to __subsf3
define float @neg_then_add(float noundef %a, float noundef %b) {
; CHECK-LABEL: neg_then_add:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    { st32 lr, sp, 3; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset lr, 12
; CHECK-NEXT:    { move32 r3, r1; move32 r1, r2 }
; CHECK-NEXT:    { move32 r2, r3; nop }
; CHECK-NEXT:    { jal_w lr, __subsf3; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 3; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %na = fneg float %a
  %r = fadd float %na, %b
  ret float %r
}
