; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 < %s | FileCheck %s

; Fixed-size stack allocation
define i32 @test_alloca() {
; CHECK-LABEL: test_alloca:
; CHECK:       // #<spill-kpi> @test_alloca spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    { addi32 r1, r0, 42; addi32 r2, sp, 12 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r1, r2, 0 }
; CHECK-NEXT:    { s_lw_with_imm r1, r2, 0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 16; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %p = alloca i32
  store i32 42, ptr %p
  %v = load i32, ptr %p
  ret i32 %v
}

; Callee-saved registers
define i32 @test_callee_save() {
  ; Force use of many registers to test callee-save
; CHECK-LABEL: test_callee_save:
; CHECK:       // #<spill-kpi> @test_callee_save spills=4 spill-bytes=16 reloads=4 reload-bytes=16
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    { addi32 r1, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm lr, r1, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r10, r1, 1 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r9, r1, 2 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r8, r1, 3 }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset r8, 20
; CHECK-NEXT:    .cfi_offset r9, 16
; CHECK-NEXT:    .cfi_offset r10, 12
; CHECK-NEXT:    .cfi_offset lr, 8
; CHECK-NEXT:    { addi32 r1, r0, 1; addi32 r8, r0, 2 }
; CHECK-NEXT:    { addi32 r9, r0, 3; nop }
; CHECK-NEXT:    { nop; jal lr, extern_func; nop }
; CHECK-NEXT:    { move32 r10, r1; move32 r1, r8; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, extern_func; nop }
; CHECK-NEXT:    { move32 r8, r1; move32 r1, r9; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { nop; jal lr, extern_func; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; add32 r2, r10, r8; nop }
; CHECK-NEXT:    { add32 r1, r2, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm lr, sp, 2; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r10, sp, 3; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r9, sp, 4; nop; nop }
; CHECK-NEXT:    { s_lw_with_imm r8, sp, 5; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 24; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v1 = call i32 @extern_func(i32 1)
  %v2 = call i32 @extern_func(i32 2)
  %v3 = call i32 @extern_func(i32 3)
  %r = add i32 %v1, %v2
  %r2 = add i32 %r, %v3
  ret i32 %r2
}
declare i32 @extern_func(i32)
