; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s

; Role: semantic — Haydn uses 8-byte stack alignment.


;
; Haydn uses 8-byte stack alignment. SP adjustments must be multiples of 8.

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped


declare void @sink(ptr)
declare i32 @many_params(i32, i32, i32, i32, i32, i32, i32, i32, i32)

; 3 x i32 = 12 → pad to multiple of 8
define void @test_multi_alloca() {
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; CHECK-LABEL: test_multi_alloca:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 24; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, sp, 20; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 16; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 1; nop }
; CHECK-NEXT:    { st32 r4, r1, 0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 2; nop }
; CHECK-NEXT:    { st32 r1, r2, 0; nop }
; CHECK-NEXT:    { addi32_w r3, sp, 12; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 3; nop }
; CHECK-NEXT:    { st32 r1, r3, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 24; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %a = alloca i32
  %b = alloca i32
  %c = alloca i32
  store i32 1, ptr %a
  store i32 2, ptr %b
  store i32 3, ptr %c
  ret void
}

define void @test_256_bytes() {
; CHECK-LABEL: test_256_bytes:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 264; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 264
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, sp, 8; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 0; nop }
; CHECK-NEXT:    { st32 r2, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 264; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %arr = alloca [64 x i32], align 8
  %p = getelementptr [64 x i32], ptr %arr, i32 0, i32 0
  store i32 0, ptr %p
  ret void
}

define void @test_512_bytes() {
; CHECK-LABEL: test_512_bytes:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 520; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 520
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, sp, 8; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 42; nop }
; CHECK-NEXT:    { st32 r2, r1, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 520; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %arr = alloca [128 x i32], align 8
  %p = getelementptr [128 x i32], ptr %arr, i32 0, i32 0
  store i32 42, ptr %p
  ret void
}

define i32 @test_odd_alloca(i32 %a) {
; 7 x i32 = 28 → pad to 32 or 40
; CHECK-LABEL: test_odd_alloca:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 40; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 8; nop }
; CHECK-NEXT:    { st32 r1, r2, 0; nop }
; CHECK-NEXT:    { ld32 r1, r2, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 40; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %arr = alloca [7 x i32], align 8
  %p = getelementptr [7 x i32], ptr %arr, i32 0, i32 0
  store i32 %a, ptr %p
  %v = load i32, ptr %p
  ret i32 %v
}

define void @test_nested_stack() {
; CHECK-LABEL: test_nested_stack:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 144; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 140; nop }
; CHECK-NEXT:    { st32_reg lr, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 144
; CHECK-NEXT:    .cfi_offset lr, 140
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, sp, 8; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 42; nop }
; CHECK-NEXT:    { st32 r2, r1, 0; nop }
; CHECK-NEXT:    { jal_w lr, sink; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r0, r0, 140; nop }
; CHECK-NEXT:    { ld32_reg lr, sp, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 144; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %arr = alloca [32 x i32], align 8
  %p = getelementptr [32 x i32], ptr %arr, i32 0, i32 0
  store i32 42, ptr %p
  call void @sink(ptr %p)
  ret void
}

define i32 @test_stack_outgoing(i32 %a) {
; CHECK-LABEL: test_stack_outgoing:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 32; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 24; nop }
; CHECK-NEXT:    { st32 lr, r2, 0; nop }
; CHECK-NEXT:    { st32 r8, r2, 1; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset r8, 28
; CHECK-NEXT:    .cfi_offset lr, 24
; CHECK-NEXT:    { subi32 sp, sp, 16; move32 r12, r1 }
; CHECK-NEXT:    { addi32_w r2, r0, 8; nop }
; CHECK-NEXT:    { move32 r8, sp; nop }
; CHECK-NEXT:    { st32_post r2, r8, 2; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 1; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 2; nop }
; CHECK-NEXT:    { addi32_w r3, r0, 3; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 4; nop }
; CHECK-NEXT:    { addi32_w r5, r0, 5; nop }
; CHECK-NEXT:    { addi32_w r6, r0, 6; nop }
; CHECK-NEXT:    { addi32_w r7, r0, 7; nop }
; CHECK-NEXT:    { st32 r12, r8, 0; nop }
; CHECK-NEXT:    { jal_w lr, many_params; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 6; nop }
; CHECK-NEXT:    { ld32 r8, sp, 7; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 32; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %r = call i32 @many_params(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 %a)
  ret i32 %r
}

define i32 @test_local_and_outgoing(i32 %a) {
; CHECK-LABEL: test_local_and_outgoing:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 48; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 40; nop }
; CHECK-NEXT:    { st32 lr, r2, 0; nop }
; CHECK-NEXT:    { st32 r8, r2, 1; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    .cfi_offset r8, 44
; CHECK-NEXT:    .cfi_offset lr, 40
; CHECK-NEXT:    { addi32_w r6, sp, 24; nop }
; CHECK-NEXT:    { subi32 sp, sp, 16; st32 r1, r6, 0 }
; CHECK-NEXT:    { addi32_w r2, r0, 8; nop }
; CHECK-NEXT:    { move32 r12, sp; ld32 r1, r6, 0 }
; CHECK-NEXT:    { st32_post r2, r12, 2; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 2; nop }
; CHECK-NEXT:    { addi32_w r3, r0, 3; nop }
; CHECK-NEXT:    { addi32_w r4, r0, 4; nop }
; CHECK-NEXT:    { addi32_w r5, r0, 5; nop }
; CHECK-NEXT:    { addi32_w r6, r0, 6; nop }
; CHECK-NEXT:    { addi32_w r7, r0, 7; nop }
; CHECK-NEXT:    { addi32_w r8, r0, 9; nop }
; CHECK-NEXT:    { st32 r8, r12, 0; nop }
; CHECK-NEXT:    { jal_w lr, many_params; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 16; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { ld32 lr, sp, 10; nop }
; CHECK-NEXT:    { ld32 r8, sp, 11; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 48; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %arr = alloca [4 x i32], align 8
  %p = getelementptr [4 x i32], ptr %arr, i32 0, i32 0
  store i32 %a, ptr %p
  %v = load i32, ptr %p
  %r = call i32 @many_params(i32 %v, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9)
  ret i32 %r
}

; 5 x i32 = 20 → pad to multiple of 8
define void @test_align_5xi32() {
; CHECK-LABEL: test_align_5xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 32; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r1, sp, 28; nop }
; CHECK-NEXT:    { addi32_w r2, sp, 24; nop }
; CHECK-NEXT:    { addi32_w r6, r0, 1; nop }
; CHECK-NEXT:    { st32 r6, r1, 0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 2; nop }
; CHECK-NEXT:    { st32 r1, r2, 0; nop }
; CHECK-NEXT:    { addi32_w r3, sp, 20; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 3; nop }
; CHECK-NEXT:    { st32 r1, r3, 0; nop }
; CHECK-NEXT:    { addi32_w r4, sp, 16; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 4; nop }
; CHECK-NEXT:    { st32 r1, r4, 0; nop }
; CHECK-NEXT:    { addi32_w r5, sp, 12; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 5; nop }
; CHECK-NEXT:    { st32 r1, r5, 0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 32; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
  %a = alloca i32
  %b = alloca i32
  %c = alloca i32
  %d = alloca i32
  %e = alloca i32
  store i32 1, ptr %a
  store i32 2, ptr %b
  store i32 3, ptr %c
  store i32 4, ptr %d
  store i32 5, ptr %e
  ret void
}
