; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -O2 < %s | FileCheck %s

; Role: smoke — Smoke: pre-existing CHECK drift — compile and emit a return.

; Smoke: pre-existing CHECK drift — compile and emit a return.
;
; REBASELINED : / pipeline reorder (ExpandPseudos/BitSimplify pre-scheduler + materialize at leaveRegion) — bundles regrouped, ops unchanged.
;
; Test switch statement lowering.
; Small switches (< 4 dense cases) use comparison + branch chains.
; Dense switches (>= 4 consecutive cases) use jump tables (see switch-jump-table.ll).

;Small switch (2 cases)

define i32 @switch_2_cases(i32 %x) {
; CHECK-LABEL: switch_2_cases:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 1; nop }
; CHECK-NEXT:    { seq32 r2, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r2, .LBB0_3; nop }
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    { addi32_w r2, r0, 0; nop }
; CHECK-NEXT:    { seq32 r1, r1, r2; nop }
; CHECK-NEXT:    { xori32 r1, r1, 1; nop }
; CHECK-NEXT:    { bnez_w r1, .LBB0_4; nop }
; CHECK-NEXT:  // %bb.2: // %case0
; CHECK-NEXT:    { addi32_w r1, r0, 10; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB0_5; nop }
; CHECK-NEXT:  .LBB0_3: // %case1
; CHECK-NEXT:    { addi32_w r1, r0, 20; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB0_5; nop }
; CHECK-NEXT:  .LBB0_4: // %default
; CHECK-NEXT:    { move32 r1, r2; nop }
; CHECK-NEXT:  .LBB0_5: // %case0
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
switch i32 %x, label %default [
  i32 0, label %case0
  i32 1, label %case1
]

case0:
  ret i32 10

case1:
  ret i32 20

default:
  ret i32 0
}

;Small switch (3 cases)
define i32 @switch_3_cases(i32 %x) {
; CHECK-LABEL: switch_3_cases:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 3; nop }
; CHECK-NEXT:    { seq32 r2, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r2, .LBB1_5; nop }
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    { addi32_w r2, r0, 2; nop }
; CHECK-NEXT:    { seq32 r2, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r2, .LBB1_4; nop }
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    { addi32_w r2, r0, 1; nop }
; CHECK-NEXT:    { seq32 r1, r1, r2; nop }
; CHECK-NEXT:    { xori32 r1, r1, 1; nop }
; CHECK-NEXT:    { bnez_w r1, .LBB1_6; nop }
; CHECK-NEXT:  // %bb.3: // %case1
; CHECK-NEXT:    { addi32_w r1, r0, 100; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB1_7; nop }
; CHECK-NEXT:  .LBB1_4: // %case2
; CHECK-NEXT:    { addi32_w r1, r0, 200; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB1_7; nop }
; CHECK-NEXT:  .LBB1_5: // %case3
; CHECK-NEXT:    { addi32_w r1, r0, 300; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB1_7; nop }
; CHECK-NEXT:  .LBB1_6: // %default
; CHECK-NEXT:    { addi32_w r1, r0, 0; nop }
; CHECK-NEXT:  .LBB1_7: // %case1
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
switch i32 %x, label %default [
  i32 1, label %case1
  i32 2, label %case2
  i32 3, label %case3
]

case1:
  ret i32 100

case2:
  ret i32 200

case3:
  ret i32 300

default:
  ret i32 0
}

;Switch with consecutive values (4 cases → jump table)
define i32 @switch_consecutive(i32 %x) {
; switch_consecutive:
; Range check: post- the sltu+bltu_w fusion no longer fires; the range
; check is emitted as a sltu32 + bnez_w pair (semantically equivalent).
; CHECK-LABEL: switch_consecutive:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { move32 r2, r1; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 3; nop }
; CHECK-NEXT:    { sltu32 r3, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r3, .LBB2_5; nop }
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    { lui r3, .LJTI2_0; nop }
; CHECK-NEXT:    { addi32_w r3, r3, .LJTI2_0; nop }
; CHECK-NEXT:    { slli32 r2, r2, 2; nop }
; CHECK-NEXT:    { add32 r2, r3, r2; nop }
; CHECK-NEXT:    { ld32 r2, r2, 0; nop }
; CHECK-NEXT:    { jalr_w r0, r2, 0; nop }
; CHECK-NEXT:  .LBB2_2: // %case0
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 0; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB2_6; nop }
; CHECK-NEXT:  .LBB2_3: // %case1
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 1; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB2_6; nop }
; CHECK-NEXT:  .LBB2_4: // %case2
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w r1, r0, 2; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB2_6; nop }
; CHECK-NEXT:  .LBB2_5: // %default
; CHECK-NEXT:    { addi32_w r1, r0, -1; nop }
; CHECK-NEXT:  .LBB2_6: // %case3
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
switch i32 %x, label %default [
  i32 0, label %case0
  i32 1, label %case1
  i32 2, label %case2
  i32 3, label %case3
]

case0:
  ret i32 0

case1:
  ret i32 1

case2:
  ret i32 2

case3:
  ret i32 3

default:
  ret i32 -1
}

;Switch with sparse values
define i32 @switch_sparse(i32 %x) {
; CHECK-LABEL: switch_sparse:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 1000; nop }
; CHECK-NEXT:    { seq32 r2, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r2, .LBB3_5; nop }
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    { addi32_w r2, r0, 100; nop }
; CHECK-NEXT:    { seq32 r2, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r2, .LBB3_4; nop }
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    { addi32_w r2, r0, 10; nop }
; CHECK-NEXT:    { seq32 r1, r1, r2; nop }
; CHECK-NEXT:    { xori32 r1, r1, 1; nop }
; CHECK-NEXT:    { bnez_w r1, .LBB3_6; nop }
; CHECK-NEXT:  // %bb.3: // %case10
; CHECK-NEXT:    { addi32_w r1, r0, 1; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB3_7; nop }
; CHECK-NEXT:  .LBB3_4: // %case100
; CHECK-NEXT:    { addi32_w r1, r0, 2; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB3_7; nop }
; CHECK-NEXT:  .LBB3_5: // %case1000
; CHECK-NEXT:    { addi32_w r1, r0, 3; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB3_7; nop }
; CHECK-NEXT:  .LBB3_6: // %default
; CHECK-NEXT:    { addi32_w r1, r0, 0; nop }
; CHECK-NEXT:  .LBB3_7: // %case10
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
switch i32 %x, label %default [
  i32 10, label %case10
  i32 100, label %case100
  i32 1000, label %case1000
]

case10:
  ret i32 1

case100:
  ret i32 2

case1000:
  ret i32 3

default:
  ret i32 0
}

;Switch with negative values
define i32 @switch_negative(i32 %x) {
; switch_negative:
; Cmp+branch fusion no longer fires; eq+branch lowered as seq32+bnez_w.
; CHECK-LABEL: switch_negative:
; CHECK:       // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    { nop; nop }
; CHECK-NEXT:    { addi32_w r2, r0, 1; nop }
; CHECK-NEXT:    { seq32 r3, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r3, .LBB4_3; nop }
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    { addi32_w r2, r0, 0; nop }
; CHECK-NEXT:    { seq32 r3, r1, r2; nop }
; CHECK-NEXT:    { bnez_w r3, .LBB4_3; nop }
; CHECK-NEXT:  // %bb.2:
; CHECK-NEXT:    { addi32_w r2, r0, -1; nop }
; CHECK-NEXT:    { seq32 r1, r1, r2; nop }
; CHECK-NEXT:    { xori32 r1, r1, 1; nop }
; CHECK-NEXT:    { bnez_w r1, .LBB4_4; nop }
; CHECK-NEXT:  .LBB4_3: // %case_neg1
; CHECK-NEXT:    { move32 r1, r2; nop }
; CHECK-NEXT:    { beqz_w r0, .LBB4_5; nop }
; CHECK-NEXT:  .LBB4_4: // %default
; CHECK-NEXT:    { addi32_w r1, r0, 99; nop }
; CHECK-NEXT:  .LBB4_5: // %case_neg1
; CHECK-NEXT:    { xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { addi32_w sp, sp, 8; nop }
; CHECK-NEXT:    { jalr_w r0, lr, 0; nop }
switch i32 %x, label %default [
  i32 -1, label %case_neg1
  i32 0, label %case0
  i32 1, label %case1
]

case_neg1:
  ret i32 -1

case0:
  ret i32 0

case1:
  ret i32 1

default:
  ret i32 99
}
