; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -verify-machineinstrs -global-isel-abort=1 %s -o - | FileCheck %s

;
; REGRESSION TEST: VLA + call — the epilogue must restore callee-saved GPRs
; from SP (R13), not via a stale R12 base pointer.
;
; VLA forces hasFP(MF)==true (the dynamic stack allocation requires a frame
; pointer so SP can be restored). The prologue materialises the usual
; R12 = SP + off base for the CSR stores. If the matching epilogue ADDI32
; R12, SP, off is dead-code eliminated (because R12 is a reserved AT scratch
; with no live range), the LD32 rt, R12, off in the epilogue would read a
; clobbered value — losing saved LR (R15) and R8 across the call.
;
; Codex MEDIUM-3 concern (review): VLA may interact with the SP-restore
; path in a way that loses saved registers. This test exercises exactly that
; path.
;
; Expected (correct) epilogue: restore from SP after SP = FP - StackSize.
; FP (R14) is architectural frame pointer (BP folded in); CSR bank saves it.

declare void @use(ptr)

define i32 @vla_call_sp_restore(i32 %n) nounwind {
; Epilogue must restore callee-saved regs directly from SP (R13).
; CHECK-LABEL: vla_call_sp_restore:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0 }
; CHECK-NEXT:    { subi32 sp, sp, 24 }
; CHECK-NEXT:    { addi32_w r2, sp, 12 }
; CHECK-NEXT:    { st32 lr, r2, 0 }
; CHECK-NEXT:    { st32 fp, r2, 4 }
; CHECK-NEXT:    { st32 r8, r2, 8 }
; CHECK-NEXT:    { addi32_w fp, sp, 24 }
; CHECK-NEXT:    { addi32_w r2, r0, 2 }
; CHECK-NEXT:    { sll32 r1, r1, r2 }
; CHECK-NEXT:    { addi32_w r2, r0, 7 }
; CHECK-NEXT:    { add32 r1, r1, r2 }
; CHECK-NEXT:    { addi32_w r2, r0, -8 }
; CHECK-NEXT:    { and32 r1, r1, r2 }
; CHECK-NEXT:    { sub32 r8, sp, r1 }
; CHECK-NEXT:    { move32 r1, r8 }
; CHECK-NEXT:    { jal_w lr, use }
; CHECK-NEXT:    { ld32 r1, r8, 0; xor32 r0, r0, r0; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0 }
; CHECK-NEXT:    { addi32_w sp, fp, -24 }
; CHECK-NEXT:    { ld32 lr, sp, 12 }
; CHECK-NEXT:    { ld32 fp, sp, 16 }
; CHECK-NEXT:    { ld32 r8, sp, 20 }
; CHECK-NEXT:    { addi32_w sp, sp, 24 }
; CHECK-NEXT:    { jalr_w r0, lr, 0 }
entry:
  %v = alloca i32, i32 %n
  call void @use(ptr %v)
  %ret = load i32, ptr %v
  ret i32 %ret
}
