; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -verify-machineinstrs -global-isel-abort=1 %s -o - | FileCheck %s

; Role: semantic — VLA + call — the epilogue must restore callee-saved GPRs from SP (R13), not via a stale R12 base pointer.


;
; REGRESSION TEST: VLA + call — the epilogue must restore callee-saved GPRs
; from SP (R13), not via a stale R12 base pointer.
;
; VLA forces hasFP(MF)==true (the dynamic stack allocation requires a frame
; pointer so SP can be restored). The prologue materialises the usual
; R12 = SP + off base for the CSR stores. If the matching epilogue ADDI32
; R12, SP, off is dead-code eliminated (because R12 is a reserved AT scratch
; with no live range), the LD32 rt, R12, off in the epilogue would read a
; clobbered value — losing saved LR (R15) and R8 across the call.
;
; Codex MEDIUM-3 concern (review): VLA may interact with the SP-restore
; path in a way that loses saved registers. This test exercises exactly that
; path.
;
; Expected (correct) epilogue: restore from SP after SP = FP - StackSize.
; FP (R14) is architectural frame pointer (BP folded in); CSR bank saves it.
; nounwind: no .cfi_* (CFA FP+0 is covered by frame-alloca.ll / unwind-frame-chain.ll).
; Post-RA packs `move32 sp, r8` with the arg copy `move32 r1, r8` (same value).

; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped


declare void @use(ptr)

define i32 @vla_call_sp_restore(i32 %n) nounwind {
; Epilogue must restore callee-saved regs directly from SP (R13).
; REBASELINED (auto) B3.exit.4 Desc-only Format E print (S0-S1-S2 / setDesc members); .file skipped
; CHECK-LABEL: vla_call_sp_restore:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    { xor32 r0, r0, r0; subi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; addi32 r2, sp, 12 }
; CHECK-NEXT:    { nop; st32 lr, r2, 0 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 fp, r2, 1 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; st32 r8, r2, 2 } // 4-byte Folded Spill
; CHECK-NEXT:    // 4-byte Spill
; CHECK-NEXT:    { nop; addi32 fp, sp, 24 }
; CHECK-NEXT:    { slli32 r1, r1, 2; addi32 r2, r0, -8 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 7 }
; CHECK-NEXT:    { nop; and32 r1, r1, r2 }
; CHECK-NEXT:    { nop; addi32 r1, r1, 7 }
; CHECK-NEXT:    { nop; and32 r1, r1, r2 }
; CHECK-NEXT:    { nop; sub32 r1, sp, r1 }
; CHECK-NEXT:    { nop; and32 r8, r1, r2 }
; CHECK-NEXT:    { nop; lui r2, use }
; CHECK-NEXT:    { nop; addi32 r2, r2, use }
; CHECK-NEXT:    { nop; move32 sp, r8; move32 r1, r8 }
; CHECK-NEXT:    { jalr lr, r2, 0 }
; CHECK-NEXT:    { xor32 r0, r0, r0; ld32 r1, r8, 0 }
; CHECK-NEXT:    { nop; xor32 r0, r0, r0 }
; CHECK-NEXT:    { nop; addi32 sp, fp, -24 }
; CHECK-NEXT:    { ld32 fp, sp, 4; ld32 lr, sp, 3 }
; CHECK-NEXT:    { nop; ld32 r8, sp, 5 }
; CHECK-NEXT:    { nop; addi32 sp, sp, 24 }
; CHECK-NEXT:    { nop; jalr r0, lr, 0 }
; T-ABI2: legalizer rounds size to 8 and ANDs SP with -8 (may re-round
; after IRTranslator). Do not pin physregs for that sequence.
entry:
  %v = alloca i32, i32 %n
  call void @use(ptr %v)
  %ret = load i32, ptr %v
  ret i32 %ret
}
