//===- HaydnThunks.cpp ----------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Haydn long-branch / long-call thunks (G-LLD-VENEER).
//
// Format E parcels are 12 bytes. HI12/LO20 materialize the target into a
// borrowable soft-zero R0, then JALR jumps.
//
// Unified call + branch veneer — 3 parcels (36 B), no R12:
//   LUI    R0, hi12(target+addend)
//   ADDI32 R0, R0, lo20(...)
//   JALR   R0, R0, 0          // PC=target; R0=link (never falls through)
//
// Why R0, not R12:
//   * R0 is soft-zero and product law allows borrow (prologue re-zeros on
//     entry; mid-fn far branch leaves R0=link — documented residual).
//   * R12 is a normal caller-saved allocatable GPR — do not permanently
//     reserve it as linker AT (no free AT).
//   * Call sites already use JAL/JAL_W → LR (R15) holds the real return
//     address; veneer must not clobber LR. JALR rd=R0 preserves LR.
//   * Branch sites do not need a stack save of R12; R0 is free scratch.
//
// Relocation addend is honored. getThunkSectionSpacing() lives in Haydn.cpp.
//
//===----------------------------------------------------------------------===//

#include "HaydnThunks.h"

#include "InputSection.h"
#include "OutputSections.h"
#include "Symbols.h"
#include "SyntheticSections.h"
#include "Target.h"
#include "Thunks.h"
#include "lld/Common/CommonLinkerContext.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/MathExtras.h"

using namespace llvm;
using namespace llvm::object;
using namespace llvm::ELF;
using namespace llvm::support;
using namespace lld;
using namespace lld::elf;

namespace {

/// One format E bundle: 96 bits, so a whole uint64 plus a uint32. Emphatically
/// not two limbs — writing two uint64s here is what ran the old Bundle128
/// veneer four bytes into the next parcel (FORMAT-E-SWITCH-PLAN.md § 5.2).
constexpr unsigned HaydnBundleBytes = 12;

/// The veneer's three instructions, as generated bundle words. Hand-written
/// constants here were Bundle128's and stayed Bundle128's across the switch;
/// nothing in the compiler's own gates can see lld, so the veneer quietly
/// became undecodable. Generated by
/// `haydn_encoding.py --emit thunk-encoding`, which is the same file that
/// places the fields.
struct ThunkInsn {
  uint64_t Lo;
  uint32_t Hi;
  unsigned ImmLsb;   ///< bundle bit
  unsigned ImmWidth;
};

#define HAYDN_THUNK_INSN_LIST(...) __VA_ARGS__
#define HAYDN_THUNK_INSN(Name, Lo, Hi, ImmLsb, ImmWidth)                       \
  static constexpr ThunkInsn Insn##Name = {Lo, Hi, ImmLsb, ImmWidth};
#include "HaydnThunkEncoding.inc"
#undef HAYDN_THUNK_INSN
#undef HAYDN_THUNK_INSN_LIST

/// Write one bundle, with \p Imm placed at the instruction's immediate field.
/// The field can straddle bit 64, so the shift is done on both halves rather
/// than assuming it lands in the low one.
static void writeThunkInsn(uint8_t *Buf, const ThunkInsn &I, uint32_t Imm) {
  uint64_t Mask = I.ImmWidth >= 64 ? ~0ull : ((1ull << I.ImmWidth) - 1);
  uint64_t Value = static_cast<uint64_t>(Imm) & Mask;

  uint64_t Lo = I.Lo;
  uint32_t Hi = I.Hi;
  if (I.ImmLsb < 64) {
    Lo |= Value << I.ImmLsb;
    if (unsigned Spill = 64 - I.ImmLsb; Spill < 64)
      Hi |= static_cast<uint32_t>(Value >> Spill);
  } else {
    Hi |= static_cast<uint32_t>(Value << (I.ImmLsb - 64));
  }

  endian::write64le(Buf, Lo);
  endian::write32le(Buf + 8, Hi);
}

static void splitHiLo(uint64_t TargetVA, uint32_t &Hi12, uint32_t &Lo20) {
  uint64_t Hi = (TargetVA + 0x80000ull) >> 20;
  int64_t Lo =
      static_cast<int64_t>(TargetVA) - static_cast<int64_t>(Hi << 20);
  assert(Hi <= 0xFFFu && "HI12 out of range for LUI");
  assert(isInt<20>(Lo) && "LO20 out of range for ADDI32");
  Hi12 = static_cast<uint32_t>(Hi);
  Lo20 = static_cast<uint32_t>(Lo) & 0xFFFFFu;
}

/// Far call / far branch veneer. Borrows soft-zero R0; never touches R12/LR.
/// Size: 3 × 12 = 36 bytes.
///
/// The addend needs correcting, and this is easy to miss. A branch resolves
/// from the BUNDLE, not from the entry it happens to sit in, so the emitter
/// puts the entry's byte base into the addend and the relocation's offset
/// points at the entry. For a PC-relative patch the two cancel: S + A - P has
/// the base in both A and P. A veneer does not cancel anything — it
/// materializes an ABSOLUTE address — so the base has to come back out, or
/// every far call lands that many bytes past its target, mid-bundle.
///
/// It comes back out in writeTo(), NOT in the addend, and the difference
/// matters. `Thunk::addend` is what `ThunkCreator::normalizeExistingThunk()`
/// writes back into the relocation when a veneer goes out of range and the
/// call has to be re-thunked, so it has to stay equal to the addend the
/// relocation arrived with. Subtracting the base here — which is what this
/// class used to do — makes that round trip lossy, and the second veneer
/// subtracts a base that is already gone. Hexagon keeps `relOffset` as a
/// member for the same reason.
class HaydnLongThunk : public Thunk {
public:
  HaydnLongThunk(Ctx &ctx, Relocation &rel, Symbol &dest)
      : Thunk(ctx, dest, rel.addend), RelOffset(rel.offset) {
    // Align(4), not the parcel size. 12 is not a power of two and so cannot be
    // requested at all; every bundle boundary sits at 12k from the section
    // start and is therefore already 4-aligned, so the contract is satisfied
    // and the padding is always zero (FORMAT-E-SWITCH-PLAN.md § 5.9). Asking
    // for 16 here would be the same defect that took object emission from 424
    // tests to 134.
    alignment = 4;
  }
  uint64_t RelOffset;
  uint32_t size() override { return 3 * HaydnBundleBytes; }
  void writeTo(uint8_t *buf) override;
  void addSymbols(ThunkSection &isec) override;
};

void HaydnLongThunk::writeTo(uint8_t *Buf) {
  uint32_t Hi12, Lo20;
  int64_t EntryBase = int64_t(RelOffset % HaydnBundleBytes);
  splitHiLo(destination.getVA(ctx, addend - EntryBase), Hi12, Lo20);
  writeThunkInsn(Buf + 0 * HaydnBundleBytes, InsnLUI, Hi12);
  writeThunkInsn(Buf + 1 * HaydnBundleBytes, InsnADDI32, Lo20);
  writeThunkInsn(Buf + 2 * HaydnBundleBytes, InsnJALR, 0);
}

void HaydnLongThunk::addSymbols(ThunkSection &Isec) {
  addSymbol(ctx.saver.save("__haydn_thunk_" + destination.getName()), STT_FUNC,
            0, Isec);
}

} // namespace

int64_t lld::elf::haydnBundleOffset(const Relocation &Rel) {
  return int64_t(Rel.offset % HaydnBundleBytes);
}

std::unique_ptr<Thunk> lld::elf::addThunkHaydn(Ctx &ctx,
                                               const InputSection &Isec,
                                               Relocation &Rel, Symbol &S) {
  (void)Isec;
  switch (Rel.type) {
  case R_HAYDN_CallSImm20:
  case R_HAYDN_WIDE_CallSImm20:
  case R_HAYDN_BranchSImm16:
  case R_HAYDN_WIDE_BranchSImm12:
  case R_HAYDN_WIDE_BranchSImm12_RI:
    return std::make_unique<HaydnLongThunk>(ctx, Rel, S);
  default:
    Fatal(ctx) << "unrecognized relocation " << Rel.type << " to " << &S
               << " for Haydn target";
    llvm_unreachable("");
  }
}
