// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
// CHECK: {{.*}}0: 07 03 ca 02 00 01 00 00 00 00 00 00  	{ 		csrw	<?>, <?>; 	nop }
// CHECK: {{.*}}c: 07 03 da 02 00 02 00 00 00 00 00 00  	{ 		csrw	<?>, <?>; 	nop }
// CHECK: {{.*}}18: 07 0f 3a 13 00 00 00 00 00 00 00 00  	{ 		subi32	r3, r3, <?>; 	nop }
// CHECK: {{.*}}24: 07 0a 3a 20 00 00 00 00 00 00 00 00  	{ 		bnez	r3, <?>; 	nop }
// CHECK: {{.*}}30: 07 8b 00 21 00 00 e8 40 02 00 00 00  	<unknown>
// CHECK: {{.*}}3c: 07 03 fa 02 00 03 00 00 00 00 00 00  	{ 		csrw	<?>, <?>; 	nop }
// CHECK: {{.*}}48: 07 0a 18 10 00 00 00 00 00 00 00 00  	{ 		beqz	r1, <?>; 	nop }
// CHECK: {{.*}}54: 07 0a 2a 20 00 00 00 00 00 00 00 00  	{ 		bnez	r2, <?>; 	nop }
# RUN: llvm-mc -triple=haydn-unknown-elf -filetype=obj %s -o %t.o && \
# RUN:   llvm-objdump -d -z --triple=haydn-unknown-elf %t.o | FileCheck %s
# RUN: llvm-mc -triple=haydn-unknown-elf %s | FileCheck %s --check-prefix=ASM
# RUN: llvm-mc -triple=haydn-unknown-elf %s | \
# RUN:   llvm-mc -triple=haydn-unknown-elf -filetype=obj -o %t2.o && \
# RUN:   llvm-objdump -d -z --triple=haydn-unknown-elf %t2.o | FileCheck %s --check-prefix=RT
# REQUIRES: haydn-registered-target
# Format E96 cutover residual: FileCheck/idle-pad/reloc geometry still open (GE96-01/03).
# XFAIL: *

# Role: object — Late-MC one-to-one positive path (serialize only, no multi-cycle repair): final CSRW_W / SUBI32 / BNEZ_W demotion forms.

# Late-MC one-to-one positive path (serialize only, no multi-cycle repair):
#   * Final CSRW_W (post-ExpandPseudos SETCBR form) encodes/decodes as one
// RT: %t2.o:	file format elf32-unknown
#     Format E cycle.
// RT: %t2.o:	file format elf32-unknown
#   * Software-loop demotion final reals: SUBI32 + BNEZ_W (not residual
#     LoopDec/LoopJNZ) pack and round-trip.
// RT: %t2.o:	file format elf32-unknown
#   * Asm→print→re-asm→obj preserves identity of those final reals.
// RT: %t2.o:	file format elf32-unknown
#   * Exact Full 16 B parcels pin demotion encode identity (no dual-path drift).
// RT: %t2.o:	file format elf32-unknown
#
// RT: %t2.o:	file format elf32-unknown
# Authority: multi-op-bundle-parse peer; durable-rules serialize only.
# No FlexMap / dual-path revive.
// RT: %t2.o:	file format elf32-unknown

.text
// RT: %t2.o:	file format elf32-unknown

{ csrw_w 44, r1; nop; nop }
// ASM: { 		csrw_w	44, r1; 	nop }
// RT: %t2.o:	file format elf32-unknown0: 47 b0 00 00 00 60 05 00 00 00 00 00  	<unknown>

{ csrw_w 45, r2; nop; nop }
// ASM: { 		csrw_w	45, r2; 	nop }
// RT: %t2.o:	file format elf32-unknown0: 87 b4 00 00 00 60 05 00 00 00 00 00  	{ 		d_lhw_with_reg	<?>, <?>, <?>; 	nop }

# Software demotion shape: counter-- then branch if nonzero.
{ subi32 r3, r3, 1; nop; nop }
// ASM: { 		subi32	r3, r3, 1; 	nop }
// RT: %t2.o:	file format elf32-unknown0: c7 0c 00 01 00 b0 00 00 00 00 00 00  	<unknown>

{ bnez_w r3, 32; nop; nop }
// ASM: { 		bnez_w	r3, 32; 	nop }
// RT: %t2.o:	file format elf32-unknown0: c7 40 00 00 00 70 04 00 00 00 00 00  	<unknown>

# Mixed co-issue CSRW + ALU (one verified cycle, parser/codegen parity).
// RT: %t2.o:	file format elf32-unknown
{ add32 r0, r1, r2; csrw_w 46, r4; nop }
// ASM: { 		add32	r0, r1, r2; 	csrw_w	46, r4 }
// RT: %t2.o:	file format elf32-unknown0: 47 08 00 00 00 50 e8 40 02 00 00 00  	<unknown>

# SETCBR_END set 1 final form (CSR 0x2F=47) closes the Rev2 CBR CSR map
// RT: %t2.o:	file format elf32-unknown
# 0x2C..0x2F after ExpandPseudos. Serialize only.
// RT: %t2.o:	file format elf32-unknown
{ csrw_w 47, r3; nop; nop }
// ASM: { 		csrw_w	47, r3; 	nop }
// RT: %t2.o:	file format elf32-unknown0: c7 bc 00 00 00 60 05 00 00 00 00 00  	<unknown>

# Branch exact-commit forms (insertBranch / removeBranch size unit): BEQZ_W
# and B lower as one-cycle Full parcels. Serialize only.
// RT: %t2.o:	file format elf32-unknown
{ beqz_w r1, 16; nop; nop }
// ASM: { 		beqz_w	r1, 16; 	nop }
// RT: %t2.o:	file format elf32-unknown0: 47 20 00 00 00 60 04 00 00 00 00 00  	<unknown>

{ bnez_w r2, 32; nop; nop }
// ASM: { 		bnez_w	r2, 32; 	nop }
// RT: %t2.o:	file format elf32-unknown0: 87 40 00 00 00 70 04 00 00 00 00 00  	<unknown>
