; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=haydn-unknown-elf -global-isel-abort=1 -O2 \
; RUN:     -verify-machineinstrs < %s | FileCheck %s
;
; G_ABS had no vector rule at all (only legalFor {s32, s64} + min/maxScalar), so
; an SLP-formed `<2 x s32> = G_ABS` aborted with "unable to legalize
; instruction". Finish the rule with .lower() like RISCV does: the generic ABS
; expansion re-enters the legalizer for the vector sub/max.
;
; X2ABS32 exists as a format but has no pattern for generic `abs`, so legalFor
; on V2I32 is not an option. Plain .scalarize(0) is not either — it reaches
; LegalizerHelper::fewerElementsVectorMerge, which asserts "Expected vector
; types" for a unary op.

declare <2 x i32> @llvm.abs.v2i32(<2 x i32>, i1)

define void @vabs_v2i32(ptr %p) nounwind {
; CHECK-LABEL: vabs_v2i32:
; CHECK:       // #<spill-kpi> @vabs_v2i32 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { d_ldw_with_imm d0, r1, 0; addi32 r2, r0, 31 }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, sp, 0 }
; CHECK-NEXT:    { nop; nop; s_sw_with_imm r2, sp, 1 }
; CHECK-NEXT:    { d_ldw_with_imm d1, sp, 0; addi32 sp, sp, 8 }
; CHECK-NEXT:    { nop; nop; nop }
; CHECK-NEXT:    { move32_dr_l r2, d1; move32_dr_h r3, d1; nop }
; CHECK-NEXT:    { x2sra32 d1, d0, r2; nop; nop }
; CHECK-NEXT:    { x2add32 d0, d0, d1; nop; nop }
; CHECK-NEXT:    { xor64 d0, d0, d1; nop; nop }
; CHECK-NEXT:    { nop; nop; d_sdw_with_imm d0, r1, 0 }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %v = load <2 x i32>, ptr %p, align 8
  %a = call <2 x i32> @llvm.abs.v2i32(<2 x i32> %v, i1 false)
  store <2 x i32> %a, ptr %p, align 8
  ret void
}

; Scalar forms keep the native ABS32 / ABS64 path.
declare i32 @llvm.abs.i32(i32, i1)
declare i64 @llvm.abs.i64(i64, i1)

define i32 @abs_i32(i32 %x) nounwind {
; CHECK-LABEL: abs_i32:
; CHECK:       // #<spill-kpi> @abs_i32 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { abs32 r1, r1; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %a = call i32 @llvm.abs.i32(i32 %x, i1 false)
  ret i32 %a
}

define i64 @abs_i64(i64 %x) nounwind {
; CHECK-LABEL: abs_i64:
; CHECK:       // #<spill-kpi> @abs_i64 spills=0 spill-bytes=0 reloads=0 reload-bytes=0
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { subi32 sp, sp, 8; nop }
; CHECK-NEXT:    { abs64 d0, d0; nop; nop }
; CHECK-NEXT:    { xor32 r0, r0, r0; nop; nop }
; CHECK-NEXT:    { addi32 sp, sp, 8; nop }
; CHECK-NEXT:    { nop; jalr r0, lr, 0; nop }
  %a = call i64 @llvm.abs.i64(i64 %x, i1 false)
  ret i64 %a
}
